### ISSUE TITLE
reading user's .Rprofile from docker

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/xcpEngine#127]
when running from singularity the home directory gets mounted and tries to run the user's .Rprofile script. We need this not to happen

**Comment by adrose** [comment]
R can be started with a --no-init-file flag to ignore user .Rprofile's

**Comment by adrose** [comment]
Using the --vanilla option might actually make the most sense.

see here: https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html

"The command-line option --vanilla implies --no-site-file, --no-init-file, --no-environ and (except for R CMD) --no-restore"

**Comment by mattcieslak** [comment]
I'll also see what happens if we specify a username when we build the docker image. That might be the most painless route if it works
