### ISSUE TITLE
`rms` and `fd` both contain Power formulation of FD with fmriprep

### ISSUE THREAD

**Issue by rciric** [PennBBL/xcpEngine#133]
Currently, fmriprep implements the Power formulation of framewise displacement, which XCP ingresses as `rms` in `confound2`. XCP then proceeds to recompute the Power formulation as part of the `confound2` module.

As a result, the Jenkinson formulation of FD is not currently available in XCP, and the Power formulation is duplicated in reports. Furthermore, this means that the reports misrepresent the Power formulation as the Jenkinson formulation.

**Comment by a3sha2** [comment]
please can you take a lead.

**Comment by utooley** [comment]
This is still the case, correct?

**Comment by a3sha2** [comment]
this is done
