### ISSUE TITLE
fmriprep version and preproc required

### ISSUE THREAD

**Issue by jessicaflannery** [PennBBL/xcpEngine#140]
Hello!

We are having some difficulty obtaining all of the required fmriprep outputs for xcp to work. Could you please specify 1) which fmriprep version is used and 2) which preprocs are required?

We are running 2 timepoint resting state data, hoping to use "minimal" (MNI1x1x1) anatomical and then ICA_AROMA functional connectivity. So far, we have been able to successfully run part 1 of minimal, but hit errors on QCANAT (due to missing inputs). For posterity, I have also tried to see if the ICA-ARMOA functional pipeline would work (without seeds; MNI2x2x2) and it too errors quickly (due to missing inputs).

1) Most recently, we have used fmriprep 1.2.4 and 1.2.5 and we are comparing required outputs to https://figshare.com/articles/xcpEngine_tutorial_data/7359086
The logs indicate version 1.1.8 was used; however, that version does not have the same naming conventions as the tutorial data, so we were hoping you could clarify. 

2) What output-space should be specified and/or other preproc specifications? My understanding is "T1w" and "template" are needed. I included all, to be safe, but it doesn't appear all are needed: E.g., --output-space {'T1w', 'template', 'fsaverage5', 'fsnative'}. Note: we have successfully included the needed ICA-AROMA outputs.

Specific missing outputs appear to be ones that include two "space" outputs in one image, rather the the one space output. E.g., we receive the following outputs: 
"sub-TAG002_ses-wave2_task-rest_run-01_space-MNI152NLin2009cAsym_boldref.nii.gz" 
and 
"sub-TAG002_ses-wave2_task-rest_run-01_space-T1w_boldref.nii.gz" 
BUT not 
"sub-1_task-rest_space-MNI152NLin2009cAsym_desc-preproc_space-MNI152NLin2009cAsym_boldref.nii.gz"

Thank you so much for your assistance! We are excited to work within this pipeline!

**Comment by jessicaflannery** [comment]
Thank you so much for your prompt reply, Matt!

I quickly tried moving our anat files to all either be in `ses-wave2/anat` or all in subject's name anat. The first way produced an error, expecting data in subject's anat. The second way with all files in subject's name `anat` produced an error at QCANAT again indicating: 
`Error in readNifti(impath) :
 Failed to read image from path /projects/dsnlab/shared/tag/bids_data/derivatives/XCP/data/sub-TAG002/qcanat/sub-TAG002~TEMP~-fg.nii.gz
In addition: Warning message:
In readNifti(impath) :
 nifti_image_read: failed to find header file for '/projects/dsnlab/shared/tag/bids_data/derivatives/XCP/data/sub-TAG002/qcanat/sub-TAG002~TEMP~-fg.nii.gz'

Similarly, the error we receive for func is:
`· [An error occurred while processing module prestats.]
· [The error was detected at signpost @1.4.]
· [The most recent command logged was]
· [fslroi /projects/dsnlab/shared/tag/bids_data/derivatives/XCP/data/sub-TAG002/prestats/sub-TAG002~TEMP~_RPI.nii.gz /projects/dsnlab/shared/tag/bids_data/derivatives/XCP/data/sub-TAG002/prestats/sub-TAG002~TEMP~_RPI_DVO.nii.gz]
· [For additional details, view the processing log. For improved]
· [diagnostics, increment verbosity using the -t option.]
· []
· [Processing failed to produce required output: /projects/dsnlab/shared/tag/bids_data/derivatives/XCP/data/sub-TAG002/prestats/sub-TAG002~TEMP~_RPI_DVO.nii.gz]
· []
· [stream abort]`

2) As for which anatomical pipeline, our goal is to focus on functional connectivity, so my understanding was the minimal or minimal + was the best pipeline for that, since we do not plan to focus on structural analyses.  I tried it with antsct as well though and received the same error. 

If we are using the correct fmriprep version and requesting the correct outputs, do you know what else we could do to trouble shoot these errors? 

Thank you again!!

**Comment by a3sha2** [comment]
Hi Jessica,
1. Like Matt said, you dont actually need to run  structural pipeline again wit the updated xcpEnigne. if you want to run structural structural processing,  put `struc_process[1]=ACT` instead of `struc_process[1]=BFC-ABE-REG-SEG` that would avoid error but will take some few hours. 

2. for the functional processing (does not require structural processing for MNI template), the error shows that you are using the previous design file. pls look at this new design files (for 36 despike https://github.com/PennBBL/xcpEngine/blob/v0.7.0/designs/fc-36P.dsn ). The prestats only have `prestats_process[1]=FMP` which means reading  the fmriprpep output.  I noticed you want to delete some volumes, then, your prestats module  in the design file  will look like this:

```
prestats_rerun[1]=0
prestats_dvols[1]=X #  X is number of volumes you want to delete 
prestats_cleanup[1]=1
prestats_process[1]=FMP-DVO
```
You can also download updated xcpDocker image.
(may be you can share your design and cohort files)
Thanks 

Azeez

**Comment by jessicaflannery** [comment]
Hi Azeez,

Thank you so much for your prompt reply! I am currently traveling, so I apologize my responses are delayed.

That is incredibly helpful to know you don't need to run it through the anatomical xcp pipeline for our purposes! 

I also updated our design file; thank you!

I am still running into a few issues, unfortunately.
 
1) It does not recognize `FMP` as a prestat process. However, if I use the standard prestat process, that section runs without error (i.e., `prestats_process[1]=DVO-MPR-STM-MCO-BXT-DMT` ). Am I also missing another update for `FMP` or `FMP-DVO` to work? 

2) It quickly errors (when I use the templated prestat_process, however, at coreg. "[Failed to import required variable: targetReference[2]]"

I'm curious if I may still have some outdated files, or incorrectly edited my cohort file. I tried a few iterations of both files to try to troubleshoot/ narrow down the error, with little luck. I changed the cohort file to reference my anatomical output from fMRI prep. I'm attaching my design and cohort file here, if that is helpful to pick out my errors. NOTE: I am attaching both at .txt files here (I do not run them at .txt).

Thank you again! I really appreciate it!

[fc-36p_new.txt](https://github.com/PennBBL/xcpEngine/files/2753872/fc-36p_new.txt)

[func_cohort.txt](https://github.com/PennBBL/xcpEngine/files/2753878/func_cohort.txt)

**Comment by a3sha2** [comment]
Hi Jessica, 
You are using previous xcpEngine, design  and cohort files. 
I want you to look at the  wiki for more information https://pipedocs.github.io. This is best and short tutorial: https://pipedocs.github.io/config/tutorial.html. 
 1. you need to download new xcpEngine. If you are using docker image, you have to pull for new docker image (https://pipedocs.github.io/containers/index.html)
2. the design files have been updated as well: for fc-36p: https://github.com/PennBBL/xcpEngine/blob/master/designs/fc-36p.dsn
if you need to delete  some volume, you need to change prestats module as follows:
```
prestats_rerun[1]=1
prestats_dvols[1]=X #  X is number of volumes you want to delete 
prestats_cleanup[1]=1
prestats_process[1]=FMP-DVO.
```

3.  you dont need to add structural directory in cohort file for fmriprep . Just need only
``` id0,img ```

Thanks.

Azeez

**Comment by sattertt** [comment]
Thanks Azeez!!  Jessica, in response to excellent feedback (from people like you!) the code has gone through several updates.  However, if you find any issues with the new version, just let us know—we really would like this to be easy to use.




Theodore D. Satterthwaite, M.D.
Assistant Professor of Psychiatry
University of Pennsylvania Perelman School of Medicine
**NOTE NEW EMAIL: sattertt@pennmedicine.upenn.edu<mailto:sattertt@pennmedicine.upenn.edu> **
www.satterthwaitelab.com<http://www.satterthwaitelab.com>

**Comment by jessicaflannery** [comment]
Thank you both for all you help! We've been going through those tutorials and online documentation as a group fairly extensively. I deleted our anatomical reference in the cohort files, but I do not see from the online documentation how else our cohort file is the wrong version? 

I reloaded the newest versions last week, but just did it again today to ensure it's the most updated one and started from scratch (and the prestat options does indeed look correct now). Unfortunately, I get the same errors "· @E.1 Invalid option detected: FMP"  during the prestat step. I'm not sure what else to update for it to recognize FMP option. I did also update our singularity image as well, but I'm currently not running through singularity due to some permission issues on our server (so pulled new repository and running xcpengine from that brand new directory). 

Thanks again!!

**Comment by mattcieslak** [comment]
@jessicaflannery you might also be running into problems with environment variables you set to run the previous version of xcpEngine. I suggest checking to make sure you don't have any environment variables related to xcp set (`env | grep -i xcp`) and if you do removing them from your startup scripts.

**Comment by jessicaflannery** [comment]
I sincerely apologize for my delayed response!! That worked (my environment was still referencing old paths) and the script does appear to be working now! Thank you SO much for all your help!
