### ISSUE TITLE
Integrating with fmriprep

### ISSUE THREAD

**Issue by robmcc10** [PennBBL/xcpEngine#141]
Hi,

Thank you for making the pipeline available! I was hoping you might be able to offer some advice in integrating fmriprep outputs (I primarily wish to use XCP for confound denoising).

I have preprocessed my data using fmriprep and have the following in my fmriprep/sub/func/ folder:

sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz
sub-01_task-rest_bold_space-MNI152NLin2009cAsym_brainmask.nii.gz
sub-01_task-rest_desc-confounds_regressors.tsv

As I don’t wish to undertake anymore preprocessing I set the prestats part of my.dsn file to:

```
###################################################################
# 1 PRESTATS
###################################################################

prestats_rerun[1]=0
prestats_cleanup[1]=1
prestats_process[1]=REF
```

I have a standard CONFOUND2 part of the .dsn file taken from the fc-36p.dsn file.

When running the prestats module I receive a couple errors:

> fslmaths /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz -mul /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask.nii.gz /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolumeBrain.nii.gz
Image Exception : #22 :: ERROR: Could not open image /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
/xcpEngine-master/core/functions/exec_fsl: line 1: 14403 Aborted                 ${FSLDIR}/bin/"${@}"
                             -   -   -
>> fslmaths /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_meanIntensity.nii.gz -mul /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask.nii.gz /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_meanIntensityBrain.nii.gz
Image Exception : #22 :: ERROR: Could not open image /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
/xcpEngine-master/core/functions/exec_fsl: line 1: 14410 Aborted                 ${FSLDIR}/bin/"${@}"
Â· @10.5 Defining spatial reference
Â· @10.6 [Adding link references]
                             -   -   -
>> rln /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~_RPI.nii.gz /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~_RPI_REF.nii.gz

And then I also receive a number of errors while the confound module is running (See below)

Any advice on how best to proceed would be much appreciated

Thanks

Rob
```

###################################################################
#  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  #
#                                                                 #
#  Â·                   CONFOUND MODEL MODULE                   Â·  #
#                                                                 #
#  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  Â·  #
###################################################################



[I][/home/k1201869/data/xcpoutput/sub-01/sub-01.nii.gz]
[O][/home/k1201869/data/xcpoutput/sub-01/confound2]
                             -   -   -
>> 0.083*2.000000
                             -   -   -
>> 0.167*2.000000
                             -   -   -
>> mkdir -p /home/k1201869/data/xcpoutput/sub-01/confound2/mc



Current processing step:
@1 Generating confound matrix
Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·
Â· @1.1 Generating temporal mask
                             -   -   -
>> ${XCPEDIR}/utils/generate_confmat.R -i -j stdVARS -o /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_dvars-std.1D
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "i" requires an argument
Execution halted
                             -   -   -
>> ${XCPEDIR}/utils/generate_confmat.R -i -j rps -o /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_realignment.1D
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "i" requires an argument
Execution halted
                             -   -   -
>> ${XCPEDIR}/utils/generate_confmat.R -i -j fd -o /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "i" requires an argument
Execution halted
Â· @1.1.1 [Computing framewise displacement]
                             -   -   -
>> ${XCPEDIR}/utils/fd.R -r /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_realignment.1D -o /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_fd.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_realignment.1D': No such file or directory
Execution halted
Â· @1.1.2 [Computing DVARS]
                             -   -   -
>> ${XCPEDIR}/utils/dvars -i /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz -o /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_dvars -s /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01~TEMP~
                             -   -   -
>> rm -f /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_spatial_sd.1D /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_ts_quality_index.1D /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_ts_outliers.1D
                             -   -   -
>> fslstats -t /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz -S
                             -   -   -
>> 3dTqual -automask /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz
                             -   -   -
>> 3dToutcount -automask /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz
                             -   -   -
>> ${XCPEDIR}/utils/featureCorrelation.R -i /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_dvars-std.1D,/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D
Â· @1.1.3 [Selecting quality criteria]
                             -   -   -
>> rm -f /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc-nFlags.1D
Â· @1.1.4 [Quality criterion:  < .166000000]
                             -   -   -
>> ${XCPEDIR}/utils/tmask.R -s /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D -t .166000000 -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01~TEMP~_-rmsMask.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D': No such file or directory
Execution halted
/xcpEngine-master/core/functions/temporal_mask: line 144: /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01~TEMP~_-rmsMask.1D: No such file or directory
                             -   -   -
>> 0/0
Runtime error (func=(main), adr=10): Divide by zero
Â· @1.1.4 [Quality criterion:  < .334000000]
                             -   -   -
>> ${XCPEDIR}/utils/tmask.R -s /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_fd.1D -t .334000000 -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01~TEMP~_-fdMask.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_fd.1D': No such file or directory
Execution halted
/xcpEngine-master/core/functions/temporal_mask: line 144: /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01~TEMP~_-fdMask.1D: No such file or directory
                             -   -   -
>> 0/0
Runtime error (func=(main), adr=10): Divide by zero
Â· @1.1.4 [Quality criterion:  < 2]
                             -   -   -
>> ${XCPEDIR}/utils/tmask.R -s /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_dvars-std.1D -t 2 -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01~TEMP~_-dvMask.1D
                             -   -   -
>> 2/256
Â· @1.1.5 [Applying framewise threshold to time series]
                             -   -   -
>> ${XCPEDIR}/utils/tmask.R -s /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc-nFlags.1D -t 0.5 -o /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_tmask.1D -m 0
Â· @1.1.6 [Evaluating data quality]
Â· @1.2 relative maximum motion
                             -   -   -
>> ${XCPEDIR}/utils/1dTool.R -i /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D -o max -f /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relMaxRMS.txt
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D': No such file or directory
Execution halted
Â· @1.3 relative mean motion
                             -   -   -
>> ${XCPEDIR}/utils/1dTool.R -i /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D -o mean -f /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relMeanRMS.txt
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_relRMS.1D': No such file or directory
Execution halted
Â· @1.2 Including realignment parameters
                             -   -   -
>> ${XCPEDIR}/utils/mbind.R -x null -y /home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_realignment.1D -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/mc/sub-01_realignment.1D': No such file or directory
Execution halted
Â· @1.5 Including csf
                             -   -   -
>> ${XCPEDIR}/utils/generate_confmat.R -i -j csf -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_csf.1D
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "i" requires an argument
Execution halted
                             -   -   -
>> ${XCPEDIR}/utils/mbind.R -x /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D -y /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_csf.1D -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D': No such file or directory
Execution halted
Â· @1.7 Including gsr
                             -   -   -
>> ${XCPEDIR}/utils/generate_confmat.R -i -j gsr -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_gsr.1D
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "i" requires an argument
Execution halted
                             -   -   -
>> ${XCPEDIR}/utils/mbind.R -x /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D -y /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_gsr.1D -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D': No such file or directory
Execution halted
Â· @1.8 Including wm
                             -   -   -
>> ${XCPEDIR}/utils/generate_confmat.R -i -j wm -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_wm.1D
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "i" requires an argument
Execution halted
                             -   -   -
>> ${XCPEDIR}/utils/mbind.R -x /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D -y /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_wm.1D -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D': No such file or directory
Execution halted
Â· @1.10 [Including 1 derivative(s)]
                             -   -   -
>> ${XCPEDIR}/utils/mbind.R -x /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D -y OPdx1 -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D': No such file or directory
Execution halted
Â· @1.11 [Including 2 power(s)]
                             -   -   -
>> ${XCPEDIR}/utils/mbind.R -x /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D -y OPpower2 -o /home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: unname -> as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/k1201869/data/xcpoutput/sub-01/confound2/sub-01_confmat.1D': No such file or directory
Execution halted
```

**Comment by a3sha2** [comment]
Hi Rob, 
You are using previous design file  of fc=36p.dsn. The current one has the following for prestats

###################################################################
# 1 PRESTATS
###################################################################
prestats_rerun[1]=0
prestats_cleanup[1]=1
prestats_process[1]=FMP

check the current design files:  https://github.com/PennBBL/xcpEngine/blob/master/designs/fc-36p.dsn 
Also you can download the updated docker image.

Best, 

Azeez

**Comment by robmcc10** [comment]
Dear Azeez,

Many thanks for your reply. I previously had:

`prestats_process[1]=FMP`

But had changed this to '=REF' as I thought this was maybe what one should do if not wanting to perform any further preprocessing

When I run the pipeline using FMP I receive the errors below which seem to suggest that some fmriprep outputs may be missing? Is it possible to use XCP with only the default fmriprep outputs, or does one always require fmriprep to be ran with `--outputs-spaces T1w`?

Thanks!

Rob

###################################################################

#                                                                 #
#               FMRI PREPROCESSING MODULE                 #
#                                                                 #
 #
###################################################################



[I][/home/k1201869/data/xcpoutput/sub-01/sub-01.nii.gz]
[O][/home/k1201869/data/xcpoutput/sub-01/prestats]
                             -   -   -
>> rln /home/k1201869/data/xcpoutput/sub-01/sub-01.nii.gz /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~.nii.gz
                             -   -   -
>> 7-5-1
                             -   -   -
>> 7-1



Current processing step:
@0 Ensure matching orientation
Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·
Â· @0.1a Input: /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~.nii.gz
Â· @0.1b Template: /xcpEngine-master/space/MNI/MNI-2x2x2.nii.gz
Â· @0.1c Output root:
Â· @0.1d checking the orientation of img and template
                             -   -   -
>> 3dinfo -orient /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~.nii.gz
                             -   -   -
>> 3dinfo -orient /xcpEngine-master/space/MNI/MNI-2x2x2.nii.gz
NATIVE:LPI TEMPLATE:RPI
Â· @0.1e img and template orientation are not the same
Â· @0.1f make it: LPI -> RPI
                             -   -   -
>> 3dresample -orient RPI -inset /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~.nii.gz -prefix /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~_RPI.nii.gz
Â· @0.1 



Current processing step:
@ getting data from frmiprep directory
Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·
                             -   -   -
>> cp /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_desc-confounds_regressors.tsv /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_fmriconf.tsv
ls: cannot access '/home/k1201869/data/fmriprep/sub-01/anat/*from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5': No such file or directory
ls: cannot access '/home/k1201869/data/fmriprep/sub-01/anat/*from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5': No such file or directory
Â· @ checking refvolume and structural orientation
                             -   -   -
>> antsApplyTransforms -e 3 -d 3 -v 0 -i /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_boldref.nii.gz -r -t -o /tmp/ref.nii.gz -n NearestNeighbor
 file /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_boldref.nii.gz does not exist . 
/xcpEngine-master/core/functions/exec_ants: line 1:  4388 Segmentation fault      ${ANTSPATH}/"${@}"
                             -   -   -
>> 3dresample -master /home/k1201869/data/xcpoutput/sub-01/sub-01.nii.gz -inset /tmp/ref.nii.gz -prefix /tmp/ref2.nii.gz
                             -   -   -
>> 3dresample -orient RPI -inset /tmp/ref2.nii.gz -prefix /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz
Â· @ checking img vol and structural orientation
                             -   -   -
>> antsApplyTransforms -e 3 -d 3 -v 0 -i /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz -r /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz -t -o /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01~TEMP~_RPI_FMP.nii.gz -n NearestNeighbor
 file /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz does not exist . 
Transform file does not exist: 1
Â· @ generate mask and referenceVolumeBrain
                             -   -   -
>> antsApplyTransforms -e 3 -d 3 -v 0 -i /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_desc-brain_mask.nii.gz -o /tmp/imgmask.nii.gz -r /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz -t -n NearestNeighbor
 file /home/k1201869/data/fmriprep/sub-01/func/sub-01_task-rest_bold_desc-brain_mask.nii.gz does not exist . 
 file /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz does not exist . 
/xcpEngine-master/core/functions/exec_ants: line 1:  7053 Segmentation fault      ${ANTSPATH}/"${@}"
                             -   -   -
>> 3dresample -master /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz -inset -prefix /tmp/structmask.nii.gz
                             -   -   -
>> fslmaths /tmp/imgmask.nii.gz -mul /tmp/structmask.nii.gz /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask.nii.gz
Cannot open volume /tmp/imgmask for reading!
Â· @ resample segmentation to img space
                             -   -   -
>> 3dresample -master /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz -inset -prefix /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_segmentation.nii.gz
                             -   -   -
>> fslmaths /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask.nii.gz -mul /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolumeBrain.nii.gz
Cannot open volume /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_mask for reading!
Â· @ generate new /home/k1201869/data/xcpoutput/sub-01/sub-01_spaces.json with spaceMetadata
                             -   -   -
>> 3dresample -master /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_referenceVolume.nii.gz -inset -prefix /home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_struct.nii.gz
/xcpEngine-master/core/functions/json_get: line 3: {}: bad substitution
source space map '/home/k1201869/data/xcpoutput/sub-01/prestats/sub-01_struct.nii.gz' is not an image
Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·
Processing step complete:
getting data from frmiprep directory
Â· @0.3 

Â· [A major error has occurred.]
Â· [The processing stream will now abort.]
Â· [Preparing diagnostics]

**Comment by a3sha2** [comment]
Hi Rob, 
You are using the previous fmriprep version. We updated the XCP to be compatible with the current version of fmriprep and as well  can read any output format  (either in t1w or MNI template).  
The best option is to rerun the fmripep with the current version. You can  the leave the output space to default or specify  `--output-space  template` . This ensure to have transformation  files required to register the  bold image (and  derivatives) to MNI template ( You wont need to run  xcp structural processing again)

Check the current output format of fmriprep with default  output space : https://figshare.com/articles/xcpEngine_tutorial_data/7359086

Best 
Azeez

**Comment by robmcc10** [comment]
Hi Azeez,

Thanks for clarifying that - I have updated to the  most recent version of fmriprep and everything works now! Thanks again for your assistance

Rob
