### ISSUE TITLE
error in ${XCPEDIR}/utils/dvars call from qcfc

### ISSUE THREAD

**Issue by traceyshi** [PennBBL/xcpEngine#147]
Hello,

I am getting the below error in the qcfc module at the calculation of dvars. 
```
· @5.1 [Computing DVARS]
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : flag "s" requires an argument
Execution halted
                             -   -   -
>> ${XCPEDIR}/utils/dvars -i /data/xcp_output/sub-6366/run-2/regress/sub-6366_run-2_residualised.nii.gz -o /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2_dvars -s /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2~TEMP~ -b /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2~TEMP~-meanIntensityBrain.nii.gz

```

When I run with the flag qcfc_cleanup[10]=0, it appears that the directory `/data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2~TEMP~` and the file `/data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2~TEMP~-meanIntensityBrain.nii.gz` do not exist. 

```
Singularity xcpEngine.simg:~> ls -la /data/xcp_output/sub-6366/run-2/qcfc/
total 17040
drwxr-xr-x  2 tracey tracey    4096 Jan 17 10:50 .
drwxr-xr-x 10 tracey tracey    4096 Jan 17 10:50 ..
-rw-r--r--  1 tracey tracey 3977055 Jan 17 10:50 sub-6366_run-2_depthMap.nii.gz
-rw-r--r--  1 tracey tracey     152 Jan 17 10:50 sub-6366_run-2_motionDVCorr.txt
-rw-r--r--  1 tracey tracey       2 Jan 17 10:50 sub-6366_run-2_tdof.txt
lrwxrwxrwx  1 tracey tracey      45 Jan 17 10:50 sub-6366_run-2~TEMP~-dn.nii.gz -> ../regress/sub-6366_run-2_residualised.nii.gz
-rw-r--r--  1 tracey tracey 6747150 Jan 17 10:50 sub-6366_run-2~TEMP~-dn-rs.nii.gz
lrwxrwxrwx  1 tracey tracey      30 Jan 17 10:50 sub-6366_run-2~TEMP~-onion.nii.gz -> sub-6366_run-2_depthMap.nii.gz
-rw-r--r--  1 tracey tracey   22959 Jan 17 10:50 sub-6366_run-2~TEMP~-onion-rs.nii.gz
-rw-r--r--  1 tracey tracey 6571519 Jan 17 10:50 sub-6366_run-2~TEMP~-pp-rs.nii.gz
-rw-r--r--  1 tracey tracey  104241 Jan 17 11:05 sub-6366_run-2_voxts.png
```
I am running xcpEngine built from Singularity/dockerhub on 1/14/19, with this design file modified from the fc-36p.dsn example
[fc-36p-tcs.txt](https://github.com/PennBBL/xcpEngine/files/2769819/fc-36p-tcs.txt). Also I should probably mention that I had issues getting singularity to pass arguments to xcpEngine (i.e. could not use `singularity run`), so I use xcpEngine by running:
```
singularity shell -B /home/tracey/dataserver:/data images/xcpEngine.simg
Singularity xcpEngine.simg:~> /neurodocker/startup.sh
Singularity xcpEngine.simg:~> /xcpEngine-master/xcpEngine -d /data/designs/fc-36p-tcs.dsn -c /data/func_cohort_SB.csv -o /data/xcp_output -t 1 -r /data
```

Am I setting this up wrong somehow? Apologies if I am missing variables for the module - I could not find an example design file that uses qcfc module. Thanks in advance.

**Comment by a3sha2** [comment]
Hi Tracey, 

Thank you. We have updated the Github and docker image. You can pull for new one.
Thanks 

Azeez

**Comment by traceyshi** [comment]
Hi Azeez,

Thanks for your quick response. I tried building an updated image, but I'm still getting the same error and the function call that fails is still the same, i.e.
`${XCPEDIR}/utils/dvars -i /data/xcp_output/sub-6366/run-2/regress/sub-6366_run-2_residualised.nii.gz -o /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2_dvars -s /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2~TEMP~ -b /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2~TEMP~-meanIntensityBrain.nii.gz
`
I also see on Github that you updated qcfc.mod, for example, to ask for *referenceVolumeBrain rather than *meanIntensityBrain, which is not reflected in the code for my qcfc.mod file, so it seems like my image did not update with your changes.

The command that I used to build the updated image was
`singularity build images/xcpEngine.simg docker://pennbbl/xcpengine:latest`
It looked like it worked and did not throw any errors.

Do I need to completely remove the previous image and build a new one from scratch?

**Comment by a3sha2** [comment]
The best thing is to rerun the `qcfc` module  by setting `qcfc_rerun=1`

**Comment by traceyshi** [comment]
I am still having the same error with attached design file 
[fc-36p-tcs.txt](https://github.com/PennBBL/xcpEngine/files/2773826/fc-36p-tcs.txt) with qcfc_rerun[10]=1

**Comment by a3sha2** [comment]
because you set `cleanup=0`, make it 1. 
you can delete `qcfc` dir and rerun

**Comment by traceyshi** [comment]
Thank you for your patience on this.

Unfortunately it's still not working. I have tried the below and get the same error:
- setting qcfc_rerun[10]=1 and qcfc_cleanup[10]=1, deleting the qcfc directory in each run, and rerunning
- setting qcfc_rerun[10]=1 and qcfc_cleanup[10]=1, deleting the entire run-1 and run-2 directories, and rerunning

**Comment by a3sha2** [comment]
Hi Tracey,

Please can you make a pull now. `singularity build images/xcpEngine.simg docker://pennbbl/xcpengine:latest`

You can test it with container before running   
`${XCPEDIR}/utils/dvars -i /data/xcp_output/sub-6366/run-2/regress/sub-6366_run-2_residualised.nii.gz -o /data/xcp_output/sub-6366/run-2/qcfc/sub-6366_run-2_dvars  -b /data/xcp_output/sub-6366/run-2/prestats/sub-6366_run-2_referenceVolumeBrain.nii.gz` 

The reference volume brain is just used for masking with `residualised.img`  which  is the main input.  `sub-6366_run-2_mask.nii.gz` can also be used in place of `/sub-6366_run-2_referenceVolumeBrain.nii.gz`

Thanks. 

Az

**Comment by traceyshi** [comment]
Hi Azeez,

Thank you so much for the detailed response. This is very helpful in locating the source of the problem: my prestats module did not generate a `*referenceVolumeBrain.nii.gz` or `*run-*_mask.nii.gz` because it could not find the correct file in the fmriprep folder. I renamed one of the fmriprep output files
`cp fmriprep/sub-6366/anat/sub-6366_desc-brain_mask.nii.gz fmriprep/sub-6366/anat/sub-6366_space-T1w_desc-brain_mask.nii.gz`, deleted the run-1 and run-2 directories, reran the entire design file, and the errors in qcfc were resolved! I also got additional output files from some other modules (e.g. norm) that I wasn't getting before but that make much more sense now. Thank you!!

I'm not sure if the fmriprep output filenames were different due to my specific setup or if fmriprep has changed their naming conventions recently -- if helpful for replication, I used fmriprep version 1.2.5 with option `--output-space T1w template` to generate the following files in my `fmriprep/sub*/anat ` folder, which seem to have similar filenames as the example [fmriprep output files](https://figshare.com/articles/xcpEngine_tutorial_data/7359086) linked in the xcpEngine pipeline tutorial.
```
[tracey@myriad dataserver]$ ls fmriprep/sub-6366/anat/
sub-6366_desc-aparcaseg_dseg.nii.gz                         sub-6366_hemi-R_inflated.surf.gii
sub-6366_desc-aseg_dseg.nii.gz                              sub-6366_hemi-R_midthickness.surf.gii
sub-6366_desc-brain_mask.nii.gz                             sub-6366_hemi-R_pial.surf.gii
sub-6366_desc-preproc_T1w.nii.gz                            sub-6366_hemi-R_smoothwm.surf.gii
sub-6366_dseg.nii.gz                                        sub-6366_label-CSF_probseg.nii.gz
sub-6366_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5  sub-6366_label-GM_probseg.nii.gz
sub-6366_from-orig_to-T1w_mode-image_xfm.txt                sub-6366_label-WM_probseg.nii.gz
sub-6366_from-T1w_to-fsnative_mode-image_xfm.txt            sub-6366_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
sub-6366_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5  sub-6366_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
sub-6366_hemi-L_inflated.surf.gii                           sub-6366_space-MNI152NLin2009cAsym_dseg.nii.gz
sub-6366_hemi-L_midthickness.surf.gii                       sub-6366_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
sub-6366_hemi-L_pial.surf.gii                               sub-6366_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
sub-6366_hemi-L_smoothwm.surf.gii                           sub-6366_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz

```
Thanks again for all of your help getting this working!

Tracey

**Comment by a3sha2** [comment]
Hi Tracey, 
Your fmriprep out for anat look completely written out. 

`sub-6366_desc-brain_mask.nii.gz` is the correct output of fmriprep and xcp suppose  pick it from `anat` dir.  we also cross checking again from our end. You can use MNI (`func/*MNI152NLin2009cAsym_desc-preproc_bold.nii.gz`) also as input. 

PS. The mask in `anat/*desc-brain_mask.nii.gz` is not using directly for masking functional image,  the bold mask (`func/*desc-brain_mask.nii.gz` ) is used. Both are in the same space but functional bold mask from `fmriprep` is not good enough, so we need to coregister  both to get finer brain mask in order to get accurate brain volume (referenceVolumeBrain) with `func/*_boldref.nii.gz`

Thanks 

Azeez

**Comment by traceyshi** [comment]
Thanks again
