### ISSUE TITLE
fslroi not working for fc-ICA-AROMA

### ISSUE THREAD

**Issue by pettitta** [PennBBL/xcpEngine#148]
I was able to successfully complete the anatomical pipleline for a test participant. Now, as I'm trying to run the test participant through the functional connectivity pipeline I'm getting an error during the preprocessing module. 

`fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize>`
`Note: indexing (in both time and space) starts with 0 not 1! Inputting -1 for a size will set it to the full image extent for that dimension.`

I've attached the error logs and the output file for reference. Is there anything I'm missing? 
[xcp_rest_error.txt](https://github.com/PennBBL/xcpEngine/files/2769985/xcp_rest_error.txt)
[xcp_rest_output.txt](https://github.com/PennBBL/xcpEngine/files/2769986/xcp_rest_output.txt)

**Comment by pettitta** [comment]
Hi Azeez,

Unfortunately, I have run fmriprep and the design file points to the fmriprep output. It won't let me upload a .dsn file but I'll paste what my cohort file looks like and upload the design file as a .txt.

[fc-ICA-AROMA_201901170904.txt](https://github.com/PennBBL/xcpEngine/files/2770096/fc-ICA-AROMA_201901170904.txt)

`id0,id1,id2,complete+,img`
`sub-SH212,ses-1,run-01,/projects/adapt_lab/shared/SHARP/bids_data/derivatives/xcpEngine/data/sub-SH212/ses-1/struc,/projects/adapt_lab/shared/SHARP/bids_data/derivatives/fmriprep/sub-SH212/ses-1/func/sub-SH212_ses-1_task-rest_run-01_space-T1w_desc-preproc_bold.nii.gz`

**Comment by a3sha2** [comment]
Hi Petita, 
Your settings is almost complete!
there are issues with your design file. 
Only need to specify `prestats_process[1]=FMP` for fmriprep. you dont need  MPR,STM,MCO and BXT, that has been done with fmriprep. The xcpengine will select  all the requirement. If you want to delete certain number of volume then you need to add DVO (delete vols) `prestats_process[1]=FMP-DVO`. then you have to include the number of volume to be deleted 
`prestats_rerun[1]=1
 prestats_dvo=x  # x is the number of first  volume to be  deleted
prestats_cleanup[1]=1
prestats_process[1]=FMP-DVO`

for the design files, you need to change the `complete+` to `antsct` 
`id0,id1,id2,antsct,img
sub-SH212,ses-1,run-01,/projects/adapt_lab/shared/SHARP/bids_data/derivatives/xcpEngine/data/sub-SH212/ses-1/struc,/projects/adapt_lab/shared/SHARP/bids_data/derivatives/fmriprep/sub-SH212/ses-1/func/sub-SH212_ses-1_task-rest_run-01_space-T1w_desc-preproc_bold.nii.gz`

**Comment by a3sha2** [comment]
for template
`standard=MNI%2x2x2`

**Comment by pettitta** [comment]
Hi Azeez,

Thank you so much! This has been very helpful. Is this what you mean for the .dsn file?

`prestats_rerun[1]=1`
`prestats_dvo=2`
`prestats_cleanup[1]=1`
`prestats_process[1]=FMP-DVO`

**Comment by a3sha2** [comment]
yes 
tha means you want to delete the first two volumes

**Comment by pettitta** [comment]
Great! Thank you so much. I'll run it and hopefully it works.

**Comment by pettitta** [comment]
Hi Azeez,

When I run it with `antsct` instead of `complete+` in the cohort file, the preprocessing doesn't even start because it says:

 @1
· @1.1
· @1.1a
· @1.1b
· @1.2
· @1.3
· @1.4
· @1.5
· ERROR
····································································



····································································
· [An error occurred while processing module localiser.]
· [The error was detected at signpost @1.5.]
· [The most recent command logged was]
· []
· [For additional details, view the processing log. For improved]
· [diagnostics, increment verbosity using the -t option.]
· []
· [Invalid path provided for antsct[9001]]
· []
· [stream abort]

**Comment by a3sha2** [comment]
the problem is the cohort file 
check the arrangement of header and path
`id0,id1,id2,antsct,img` 
`sub-SH212,ses-1,run-01,/projects/adapt_lab/shared/SHARP/bids_data/derivatives/xcpEngine/data/sub-SH212/ses-1/struc,/projects/adapt_lab/shared/SHARP/bids_data/derivatives/fmriprep/sub-SH212/ses-1/func/sub-SH212_ses-1_task-rest_run-01_space-T1w_desc-preproc_bold.nii.gz`

**Comment by pettitta** [comment]
hmm, that's odd. I'm running it as `complete` and it's working just fine but when I run it as `antsct` it's not accepting it. I checked paths and both of the directories are in the right order and exist. Does it matter that I used the `complete+` design for my anatomical instead of the `antsct`? Should I go back and run the `antsct` design instead?

**Comment by a3sha2** [comment]
Hi Pettita, 
ofcourse, it will work but `complete` is not a valid header, ithe xcp will assume you dont have not did not run the structural processing  and  use fmriprep structural output (`/anat`). 

if you have struc directory (`/struc`), `antsct` is the corresponding header. id0,id1 and id2 are just for  identification. 
id0,id1,id2,antsct,img

You dont need to rerun the structure

**Comment by pettitta** [comment]
That's great to hear! Thank you. So I do have a `/struc` directory, but whenever I run it with `antsct` it's giving me an error that it is an invalid path even though the path exists and is valid (from what I can tell). Any ideas why this might be?

**Comment by a3sha2** [comment]
can you share the log files in this directory `sub-SH212/ses-1/run-01/sub-SH212_ses-1_run-01_logs/`

**Comment by pettitta** [comment]
Sure! Here's the log file when I run it as `antsct` in the cohort file instead of `complete+`


[fc_pettitta_201901171147_sub-SH212_ses-1_run-01LOG-process.txt](https://github.com/PennBBL/xcpEngine/files/2770346/fc_pettitta_201901171147_sub-SH212_ses-1_run-01LOG-process.txt)

**Comment by a3sha2** [comment]
do you have anything in `/struc`

**Comment by pettitta** [comment]
Yes, this is currently what is in `struc`

<img width="1224" alt="screen shot 2019-01-17 at 12 00 36 pm" src="https://user-images.githubusercontent.com/1527109/51345332-8786ae80-1a4f-11e9-88e6-25c504245210.png">

**Comment by a3sha2** [comment]
pls send your cohort file (in csv)  to me in email. azeez.adebimpe@outlook.com

**Comment by a3sha2** [comment]
you have everything set perfectly. are you using docker image or not?

**Comment by pettitta** [comment]
I’m running on a supercomputer server. Do you think that may be the issue?

**Comment by a3sha2** [comment]
that is not an issue at all. Do you use singularity? 
can you post the syntax?

**Comment by pettitta** [comment]
Sorry, here's the syntax.

#!/bin/bash
#

module load singularity
module load afni
module load ants
module load fsl
module load prl
module load R
module load python3

cd /projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine

bash xcpEngine -d /projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine/fc-ICA-AROMA_201901170904.dsn \
	-c /projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine/rest_cohort.csv \
	-o /projects/adapt_lab/shared/SHARP/bids_data/derivatives/xcpEngine/data \
	-t 1 \
	-r /projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine

**Comment by a3sha2** [comment]
you dont need ` -r /projects/adapt_lab/shared/SHARP/SHARP_Scripts/rsfMRI/xcpEngine` when you bcos the cohort has full path. If you use the same process for structural pipeline. it is suppose to work

**Comment by pettitta** [comment]
Ah! That fixed it, thank you so much!
