### ISSUE TITLE
RPS map 

### ISSUE THREAD

**Issue by sedacavdaroglu** [PennBBL/xcpEngine#15]
Hi, 

I am trying to do field map correction but I am not sure what RPS stands for. Is it the phase map? What kind of a map do I need to feed in

Thanks,

**Comment by sattertt** [comment]
Hi Seda,

The dico module really is not operational for anything except a couple specific BBL datasets.  I would suggest performing distortion correction prior to feeding the functional data into XCP.

cheers,
t
