### ISSUE TITLE
How to rerun a subject

### ISSUE THREAD

**Issue by robmcc10** [PennBBL/xcpEngine#150]
Hi,

I understand that to add to an existing sample, one just adds the new subjects' path to the existing cohort file. What should one do in the case where it is necessary to tr rerun a subject that has already been processed (e.g. because there was a problem with the image files used the first time)?

Thanks!

Rob

**Comment by a3sha2** [comment]
Hi Rob, 
The best  thing you can  do is to create  a new cohort file for that  single subject then rerun all modules by specify `_rerun[cxt]=1` for all the modules.

Other option is to delete the previous run/output of that single subject and rerun with  single-subject cohort file. 

Thanks 

Az

**Comment by robmcc10** [comment]
Thanks!
