### ISSUE TITLE
Empty output from demeaning&detrending

### ISSUE THREAD

**Issue by mqlyu** [PennBBL/xcpEngine#161]
I am a new user of the xcpEnigine, and I have been getting empty output from the “Demeaning and detrending” section of the prestat module. I was able to skip that processing step by changing the design file, but I am still getting empty output from the “preparing white matter mask” step in the coreg module. Two of my colleagues ran it with the same cohort file, same design file, and the same ANTs outputs but didn’t have any problem (we have matching bash profiles). 

Any idea why this is happening?

**Cohort file**
```
id0,img,antsct
C811_AP,/data/jux/oathes_group/projects/monica/xcp_temp/input/func/811_AP/sub811_AP_denoised_B0corrected_ML.nii.gz,/data/jux/oathes_group/projects/monica/xcp_temp/input/ANTSct/C811
C811_PA,/data/jux/oathes_group/projects/monica/xcp_temp/input/func/811_PA/sub811_PA_denoised_B0corrected_ML.nii.gz,/data/jux/oathes_group/projects/monica/xcp_temp/input/ANTSct/C811
```

**Design File**
```
[design_TMSfMRI.dsn.txt](https://github.com/PennBBL/xcpEngine/files/2797593/design_TMSfMRI.dsn.txt)
```

**Comment by mattcieslak** [comment]
Hi,
It looks like you're using an old version of xcp. The entire prestats module has been removed and xcp only works on data that has been preprocessed with fmriprep.

**Comment by mqlyu** [comment]
Hi,
Thank you so much for your quick response! Are you talking about xcpEngine_060 vs.xcpEngine_061? If so, I've been trying both, but neither of them worked.

**Comment by mattcieslak** [comment]
There were lots of problems with the xcp's that did preprocessing, so we no longer support preprocessing in xcp. Instead, we require users run their data through fmriprep before xcp does the connectivity estimation. Here is some additional information: https://xcpengine.readthedocs.io/config/index.html#running-a-functional-connectivity-pipeline

**Comment by mqlyu** [comment]
Okay, I'll look into that. Thank you so much!
