### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by a3sha2** [PennBBL/xcpEngine#166]
Utilities
1.  How to get quality.csv file of the group 
2. Roiquant  with  users custom atlas 

@mattcieslak  @sattertt  @adrose 
suggestions of standalone

**Comment by sattertt** [comment]
agree-- this is critical.  we want a template for quality file and regional vals so it is consistent.  @a3sha2 we want it to look like the ones you made for f2b on pnc.

**Comment by adrose** [comment]
I have been thinking of a way to do this for a while - I want it to combine all roi metrics, and quality csv's.

How @rciric and I did this in the past was by using a very basic BASH tool I wrote see here: https://github.com/PennBBL/xcpEngine/blob/master/utils/combineOutput

It just finds all files with a common suffix and appends them to an output text file given a xcpEngine output directory

It works fine but there are certainly ways to make it more robust. Not sure if you have played around it @a3sha2 but I'd be happy to write a more robust version of this

**Comment by mattcieslak** [comment]
We have pandas and R in the container, either of these would probably be easiest to debug
