### ISSUE TITLE
Temporal filtering fails when only one volume needs to be censored

### ISSUE THREAD

**Issue by dseok** [PennBBL/xcpEngine#183]
When only one volume reaches criteria for censoring (i.e. tmask.1D only has a single 0), interpolate.py fails during the temporal filtering process in the regress module. 

A divide by zero error is thrown in lines 104, 105 and 108 of interpolate.py. The variable "timespan" is zero for those scans that only have one censored volume. The variable "seen_samples" is only one element long. The variable t_obs is an np.array listing the volume indices that are meant to be censored. 

Should another variable be used to indicate those volumes that are "seen"? As it is currently implemented, the angular_frequencies in line 112 are being calculated based on those volumes that are being censored.

**Comment by a3sha2** [comment]
Thanks @dseok 

You can pull for new docker image!

**Comment by mattcieslak** [comment]
Is this issue solved?

**Comment by a3sha2** [comment]
It is done

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
