### ISSUE TITLE
Concatenating resting state Runs

### ISSUE THREAD

**Issue by rtxj89** [PennBBL/xcpEngine#187]
Hi there, 

I don't have a specific error. But I do have a question. I have two runs of resting state per participant. I ran it through fmriprep and then xcpEngine and it's running just fine. But the output of `fcon` is for each run of resting state data but not one combine resting state file. Therefore, the connectivity matrices I get are not really usable because I'm interested in the correlations of, say, a power parcellation for both runs combined, not each separately. Is there a tool to combine resting state runs and rerun the `fcon`?

Thanks!

**Comment by a3sha2** [comment]
No.  You can combine the time series (`/*_power264_ts.1D`) and compute the correlation.
