### ISSUE TITLE
Parallelized processing

### ISSUE THREAD

**Issue by araikes** [PennBBL/xcpEngine#189]
Simple question, I hope.

I'm running xcpEngine on my data using Docker and following a modified version of the SGE example on [readthedocs](https://xcpengine.readthedocs.io/containers/index.html#using-sge-to-parallelize-across-subjects).

The next step is to run the `${XCPEDIR}/utils/combineOutput` script. How do I do that using Docker?

Thanks

**Comment by a3sha2** [comment]
The `combineOutput` is used when the users  want to combine files especially the quality control file as explained here: https://xcpengine.readthedocs.io/utils/combineoutput.html

**Comment by mattcieslak** [comment]
One option is to call it from an interactive docker session. You can use `--entrypoint bash` if you're running docker directly or `--shell` if using `xcpengine-docker`. From there you should be able to run that command directly

**Comment by araikes** [comment]
Thanks @mattcieslak . I was able to get that code working as well as the following, which more closely resembles the instructions for QC-FC:

```
docker run --rm -it \
-v /path/to/subject_folders:/data \
--entrypoint /xcpEngine/utils/combineOutput \
pennbbl/xcpengine:latest \
-p /data \
-f "*quality.vs" \
-o group/qc/xcp_qavars.csv
```
It may be worthwhile to update the documentation for xcp novices for a more explicit implication of how to call combineOutput.

As an aside, would you be willing to have perhaps an email conversation about the vision for the overall xcpEngine environment? The lab that I work in is almost exclusively CONN users when it comes to functional connectivity and I've found that I really don't enjoy CONN from a user experience. Once I got it running xcpEngine was great as far as generating connectivity matrices but I'm not fully certain of where to go from here in terms of behavioral correlates or group-wise comparisons.

I have an opportunity to learn and then teach the rest of my lab. If you're open to a conversation, I'd definitely appreciate it.

**Comment by sattertt** [comment]
Awesome, thanks for this!! We will update the documentation.  We very much appreciate your positive feedback and engagement with the software! We will continue to expand and support XCP's functionality (including ASL processing).  However, we do not plan to add many group-level analysis options; typically, we take subject-level XCP output and conduct analyses in R or python.  If you have a feature request though, please let us know!!  

Thanks again!!
ted

**Comment by araikes** [comment]
Two last things:

1. Are you guys open to pull requests. I can help edit the combineOutput .rst file. Do you have a template for PRs?

2. @sattertt I recognized in asking my question that XCP wasn't designed (currently or necessarily in the future) for second-level analyses. I was more curious about thoughts/advice on how to run the second-level analyses in R or Python (my preferred environments anyway). I want to make sure I'm doing my best to analyze the data I get out of XCP in the most accurate possible way. So again, any conversation that can be had would be greatly appreciated but I also know you all are colossally busy with your own things so I certainly do not want to take up undue amounts of your time.

Thanks
