### ISSUE TITLE
Fails on regression module with gaussian filter

### ISSUE THREAD

**Issue by mcmahonmc** [PennBBL/xcpEngine#191]
**Describe the bug**
What were you trying to do when the crash happened?
Fails on regression module with gaussian filter. 

**Cohort file**
Paste cohort file between the triple backticks
```
id0,img
sub-40728,/work/06089/mcm5324/stampede2/ADM/fmriprep/sub-40728/func/sub-40728_task-REST_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
```

**Design File**
Paste your entire design (`.dsn`) file between the triple backticks
```
#3 REGRESS

regress_tmpf[3]=gaussian
regress_hipass[3]=0
regress_lopass[3]=0.1
regress_tmpf_order[3]=
regress_tmpf_pass[3]= 
regress_tmpf_ripple[3]=
regress_tmpf_ripple2[3]=
regress_dmdt[3]=2
regress_1ddt[3]=1
regress_sptf[cxt]=none
regress_smo[cxt]=0
regress_rerun[3]=1
regress_cleanup[3]=1
regress_process[3]=TMP-REG

```
**Error message**
Paste your error message between the backticks
```
· [An error occurred while processing module regress.]
· [The error was detected at signpost @2.12c.]
· [The most recent command logged was]
· [tfilter -i /work/06089/mcm5324/stampede2/xcp_temp/sub-40728-regress-902296617~TEMP~.nii.gz -o /work/06089/mcm5324/stampede2/xcp_temp/sub-40728-regress-902296617~TEMP~_TMP.nii.gz -a 1.500000 -f gaussian -h 0 -l 0.1 -m /work/06089/mcm5324/stampede2/ADM/xcp/sub-40728/prestats/sub-40728_mask.nii.gz -1]
· [For additional details, view the processing log. For improved]
· [diagnostics, increment verbosity using the -t option.]
· []
· [Processing failed to produce required output: /work/06089/mcm5324/stampede2/xcp_temp/sub-40728-regress-902296617~TEMP~_TMP.nii.gz]
· []
· [stream abort]
```

**Runtime Information**
How were you running the software? Docker? Singularity? Directly? If Directly, please consider using Docker or Singluarity first before submitting a bug report.
Singularity

**Additional context**

**Comment by a3sha2** [comment]
if you want to remove filter, you need to change `regress_process[3]=TMP-REG` to `regress_process[3]=REG` . TMP is for temporal filtering and REG is for regression.

**Comment by mcmahonmc** [comment]
Would I still be able to do a regular low-pass filter if I removed TMP from the process? I am still interested in keeping the low-pass option.

**Comment by a3sha2** [comment]
You have to include `TMP` but cannot set hipass to zero. The best option to  is to set: 
hipass to `1/120s (0.0083Hz)` or `1/125(0.008Hz)`. lopass can be set to `nyquist`

if you set hipass to 0Hz, it is converted to seconds for Gaussian filtering (1/0=infinity). that is why it failed .

**Comment by mcmahonmc** [comment]
Thanks for that info - I changed my design file regress module to:

regress_tmpf[3]=gaussian
regress_hipass[3]=0.008
regress_lopass[3]=nyquist
regress_tmpf_order[3]=
regress_tmpf_pass[3]=
regress_tmpf_ripple[3]=
regress_tmpf_ripple2[3]=
regress_dmdt[3]=2
regress_1ddt[3]=1
regress_sptf[cxt]=none
regress_smo[cxt]=0
regress_rerun[3]=1
regress_cleanup[3]=1
regress_process[3]=TMP-REG

but I am still getting an error:

· [An error occurred while processing module regress.]
· [The error was detected at signpost @2.12c.]
· [The most recent command logged was]
· [tfilter -i /work/06089/mcm5324/stampede2/xcp_temp/sub-40728-regress-604053838~TEMP~.nii.gz -o /work/06089/mcm5324/stampede2/xcp_temp/sub-40728-regress-604053838~TEMP~_TMP.nii.gz -a 1.500000 -f gaussian -h 0.008 -l nyquist -m /work/06089/mcm5324/stampede2/ADM/xcp/sub-40728/prestats/sub-40728_mask.nii.gz -1]
· [For additional details, view the processing log. For improved]
· [diagnostics, increment verbosity using the -t option.]
· []
· [Processing failed to produce required output: /work/06089/mcm5324/stampede2/xcp_temp/sub-40728-regress-604053838~TEMP~_TMP.nii.gz]
· []
· [stream abort]

**Comment by a3sha2** [comment]
try to  start afresh in another output directory

**Comment by mcmahonmc** [comment]
I used a different output directory and now I’m getting this error:

3dTproject -input /work/06089/mcm5324/stampede2/xcp_temp/sub-30412-regress-1$
++ 3dTproject: AFNI version=AFNI_19.1.01 (Apr 18 2019) [64-bit]
++ Authored by: Cox the Algebraic (Linear)
++ Setting up regressors
++ 1 Blocks * 3 polynomials -- 3 polort regressors
^[[7m** ERROR:^[[0m -ort file #1 ((null)) is 243 long, but input dataset is 240
+ -- 8 other fixed ort regressors
^[[7m** FATAL ERROR:^[[0m Cannot continue after above errors :-( :-( :-( !!
** Program compile date = Apr 18 2019

I looked at the confmat.1D file in the regress directory and this was added to the top:

0  1  2  3  4  5  6  7
0  0  0  0  0  0  0  0
0  0  0  0  0  0  0  0

But the confmat.1D file in the confound2 directory and it’s the correct size (240). Any idea what might be up with this?

**Comment by a3sha2** [comment]
Oh. Thank you for helping us spot this. The Gaussian filter is  adding  edges to confound matrix to avoid truncation of some edge values.

We will  correct this. The `butterworth` and `Susan` are working properly
