### ISSUE TITLE
cleanup function

### ISSUE THREAD

**Issue by butellyn** [PennBBL/xcpEngine#193]
**Describe the bug**
This is not about a crash; it is about a persistent error message that isn't obviously effecting my output. It seems that whenever `/xcpEngine/core/functions/rerun` or `/xcpEngine/core/functions/cleanup` are called, I get the following error (just thought I should let you know, in case this is a problem):

**Error message**
```
line 3: ((: == 1 : syntax error: operand expected (error token is "== 1 ")
```

**Comment by a3sha2** [comment]
Thank you @butellyn 
which of the modules?

**Comment by butellyn** [comment]
I am seeing it in the following processing steps:
1) Localising design, and
2) getting data from frmiprep directory (NOTE: Should say "fmriprep")
