### ISSUE TITLE
include how to change the global file in development documentation

### ISSUE THREAD

**Issue by jdkent** [PennBBL/xcpEngine#196]
**Describe the bug**
I was trying to patch in my own development version of xcpEngine, but the environment variables were not set correctly (and I didn't track down the error very quickly). They are all redefined in the [global](https://github.com/PennBBL/xcpEngine/blob/53210815b1e9cf68e0d041ea3ca6f23fad1e20d4/core/global) file.

**Runtime Information**
I was using singularity.

**Additional context**
I think a solution would be to include more information in the [development](https://xcpengine.readthedocs.io/development.html) portion of the docs to mention to the user/developer to make sure the environment variables are set correctly.

**Comment by a3sha2** [comment]
Hi @jdkent 
Thanks you James, we will correct it in the documentation.
