### ISSUE TITLE
Failure of tmask2spkreg 

### ISSUE THREAD

**Issue by danella** [PennBBL/xcpEngine#197]
**Describe the bug**
First of all, thanks for this excellent, user-friendly set of pipelines! I am getting the following error: During Censoring: preparing spike regressors, tmask2spkreg does not seem to be working. This is the standard fc-36p_spkreg.dsn pipeline without any changes. It worked fine for another test image (from a different subject, task, and scanner); but I got the same error for another subject in this dataset; so the issue seems to be specific to this scanning protocol(?). Thanks in advance for your help with this!

**Cohort file**
```
id0,id1,img
sub-10326,ses-1,/fmriprep/sub-10326/ses-1/func/sub-10326_ses-1_task-rest_run-001_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
...,...,...

**Design File**
Paste your entire design (`.dsn`) file between the triple backticks
```
#!/usr/bin/env bash
###################################################################
# ANALYSIS VARIABLES
###################################################################

analysis=fc_$(whoami)
design=/home/danella/data/fc-36p_spkreg.dsn
sequence=anatomical
standard=MNI%2x2x2

###################################################################
# PIPELINE
###################################################################

pipeline=prestats,confound2,regress,fcon,reho,alff,roiquant,norm,qcfc

###################################################################
# 1 PRESTATS
###################################################################

prestats_rerun[1]=1
prestats_cleanup[1]=1
prestats_process[1]=FMP

###################################################################
# 2 CONFOUND2
###################################################################

confound2_rps[2]=1
confound2_rms[2]=0
confound2_wm[2]=1
confound2_csf[2]=1
confound2_gsr[2]=1
confound2_acompcor[2]=0
confound2_tcompcor[2]=0
confound2_aroma[2]=0
confound2_past[2]=0
confound2_dx[2]=1
confound2_sq[2]=2
confound2_custom[2]=
confound2_censor[2]=1
confound2_censor_contig[2]=0
confound2_framewise[2]=rmss:0.04,dv:2
confound2_rerun[2]=1
confound2_cleanup[2]=1

###################################################################
# 3  REGRESS
###################################################################

regress_tmpf[3]=butterworth
regress_hipass[3]=0.01
regress_lopass[3]=0.08
regress_tmpf_order[3]=1
regress_tmpf_pass[3]=2
regress_tmpf_ripple[3]=0.5
regress_tmpf_ripple2[3]=20
regress_dmdt[3]=2
regress_1ddt[3]=1
regress_smo[3]=6
regress_sptf[3]=susan
regress_usan[3]=default
regress_usan_space[3]=
regress_rerun[3]=0
regress_cleanup[3]=1
regress_process[3]=DMT-TMP-REG

###################################################################
# 4 FCON
###################################################################

fcon_atlas[4]=power264
fcon_metric[4]=corrcoef
fcon_thr[4]=N
fcon_window[4]=10
fcon_pad[4]=FALSE
fcon_rerun[4]=0
fcon_cleanup[4]=1

###################################################################
# 5 REHO
###################################################################

reho_nhood[5]=vertices
reho_roikw[5]=0 # does nothing at the moment
reho_sptf[5]=susan
reho_smo[5]=6
reho_rerun[5]=0
reho_cleanup[5]=1

###################################################################
# 6 ALFF
###################################################################

alff_hipass[6]=0.01
alff_lopass[6]=0.08
alff_sptf[6]=susan
alff_smo[6]=6
alff_rerun[6]=0
alff_cleanup[6]=1

###################################################################
# 7 ROIQUANT
###################################################################

roiquant_atlas[7]=power264
roiquant_globals[7]=1
roiquant_vol[7]=0
roiquant_rerun[7]=0
roiquant_cleanup[7]=1

###################################################################
# 8 NORM
###################################################################
norm_primary[8]=1
norm_rerun[8]=0
norm_cleanup[8]=1

##################################################################
# 9 QCFC
###################################################################
qcfc_atlas[9]=power264
qcfc_sig[9]=fdr
qcfc_rerun[9]=0
qcfc_cleanup[9]=1
```
**Error message**

Current processing step:
@3 Censoring: preparing spike regressors
····································································
· @3.1 Adding delta functions to model
${XCPEDIR}/utils/tmask2spkreg.R -t /home/hafemand/data/xcp_output/sub-10326/ses-1/confound2/mc/sub-10326_ses-1_tmask.1D -r /home/hafemand/data/xcp_output/sub-10326/ses-1/regress/sub-10326_ses-1~TEMP~_DMT_TMP_confmat.1D
Error in file(file, "rt") : cannot open the connection
Calls: as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/hafemand/data/xcp_output/sub-10326/ses-1/regress/sub-10326_ses-1~TEMP~_DMT_TMP_confmat.1D': No such file or directory
Execution halted
```

**Runtime Information**
Singularity

**Additional context**
I have another run (from a different protocol, subject, and scanner) that was preprocessed identically in fmriprep and ran successfully through this identical pipeline. So there is something about this particular image (or the way it was preprocessed in fmriprep) that is not working. Any guidance would be much appreciated!

**Comment by sattertt** [comment]
Hi Danella! Great to hear from you and thanks for trying this.  Azeez is at a conference but will respond later this week.

**Comment by a3sha2** [comment]
Hi @danella 

The issue is not  about scanning protocol, `xcpEngine`  works for any bold image preprocessed by FMRIPREP. The issue is that this file `/home/hafemand/data/xcp_output/sub-10326/ses-1/regress/sub-10326_ses-1~TEMP~_DMT_TMP_confmat.1D` is  not generated  during filtering of both confound regressor matrix and bold image. It is likely the bold image is bigger, that you many need to specify more RAM. 

I will be glad if you can share the log file in the directory:  `/home/hafemand/data/xcp_output/sub-10326/ses-1/ub-10326_ses-1_logs/*process`
 
Azeez 
cc @sattertt

**Comment by sattertt** [comment]
﻿Thanks Azeez!!!

**Comment by mattcieslak** [comment]
You should ask your cluster administrator how to request more memory, as  this differs depending on what queuing system you're using. It's also possible that there's not enough physical memory to hold all your data.

**Comment by danella** [comment]
I am running this using singularity, and per our administrator, this has access to the full memory of the system. We have a new system with 200GB of memory, and not many people are using it right now - so she does not think that should be a problem. I have been playing with some options to adjust memory in singularity (using --vm-ram), but none of these are working and they don't seem quite right. Any other possibilities of what could be going on? Thanks!

Best,
Danella

**Comment by a3sha2** [comment]
Hi @danella 
Are you running it on cluster with job submission or just ordinary run?

**Comment by danella** [comment]
Just an ordinary run.

**Comment by a3sha2** [comment]
please can you share one of the data with us?

**Comment by danella** [comment]
What is the best way to do that? (Dropbox? Google drive?) Thanks!

**Comment by danella** [comment]
What is your email?

**Comment by a3sha2** [comment]
azeez.adebimpe@outlook.com

**Comment by mattcieslak** [comment]
Did this get figured out?
