### ISSUE TITLE
Error using seed module on outside data

### ISSUE THREAD

**Issue by jaredpz** [PennBBL/xcpEngine#2]
I'm trying to use the seed module to do some seed-based connectivity on hcp volume data.  The data is already cleaned and warped to MNI152_2mm space, so I shouldn't need and registrations/warps, and I don't have the structural images and I have no AntsCT folders for these subjects.

I made my cohort file which consists just of subID,/path/to/BOLD

In setting up the design I tried two options.  At the beginning it asks what template you will warp to, so the first time I tried to say MNI152_2mm since that's the space I'm already in, but then when I ran the seed module I got the following errors.

Skipping analysis for:
 * 214423,/data/jag/cnds/jaredz/hcpN100Sample/subImages//214423/MNI/214423_concat4_rfMRI_REST_hp2000_clean_.nii.gz
 for the following reasons.
::XCP-ERROR: Unable to locate functional timeseries.
::XCP-ERROR: Unable to locate structural image.
::XCP-ERROR: Unable to locate warp.
::XCP-ERROR: Unable to locate inverse warp.

Then I tried to say I wouldn't be doing any normalization in my analysis and I got only the ::XCP-ERROR: Unable to locate structural image.

Is there a way to get the seed module to run on outside data that's already processed and normalized?

The two design files used are attached, hcpN100*.dsn is the first, and sgACC*.dsn is the second (nvm GitHub won't seem to let me attach them, email, slack or reply here and I'll get you any files you need)

Thanks,
Jared

**Comment by rciric** [comment]
Hello Jared,

Thanks for drawing our attention to this issue. The flagging behaviour that you noticed is definitely inappropriate; if the analyte image is in standard space, then there should not be a need for a structural image. The source of this inappropriate behaviour was the XCP Localiser. I have updated the localiser so that it only requires a structural image if the input is in native space.

```
if [[ ${space} == native ]]
   then
   [[ $(imtest ${struct[${subjidx}]}) != 1 ]] && echo "::XCP-ERROR: Unable to locate structural image." && err=1
   [[ $(imtest ${template}) != 1 ]] && echo "::XCP-ERROR: Unable to locate template." && err=1
   [[ $(imtest ${xfm_warp}) != 1 ]] && echo "::XCP-ERROR: Unable to locate warp." && err=1
   [[ $(imtest ${ixfm_warp}) != 1 ]] && echo "::XCP-ERROR: Unable to locate inverse warp." && err=1
fi
```

I can't see your design file -- could you verify that it includes the following line and then try to re-run using the most recent code?
```
space=standard
```

**Comment by jaredpz** [comment]
Sounds good, will do Rastko.

I also realized that for the HCP data I need to request 32G+ of vmem on cfn
to work with them.  Is there a way I can change hoe much vmem xscp requests
for its jobs?

I'll let you know how it works after this update

thanks,
Jared

**Comment by rciric** [comment]
XCP should automatically request the same amount of memory that you specify in your .sge_request file. In the future, we may take a look at enabling different memory settings for each module. Keep us posted as you encounter additional issues.

**Comment by jaredpz** [comment]
hmm okay, I'll try that.  I don't really want to have my default at at 32G since it will be totally excessive for most jobs, but I can work that out for now.

**Comment by rciric** [comment]
In the latest version of xcpEngine, the user is now able to specify parameters and flags for `qsub` by defining the variable `cspec` in the body of their design file (recommended placement under `ANALYSIS VARIABLES`).  For instance, a request for a specific amount of memory might look as follows:

```
cspec='-l h_vmem=32.5G,s_vmem=32.0G'
```

This feature is untested and should be used with caution, as some specifications might clash with the xcpEngine defaults in the current implementation (` -V -S /bin/bash -cwd -j y -o ${logfile}`).

At this stage, the implementation is general (for all jobs submitted by xcpEngine and associated with the provided design file); as stated, we will look into module-specific memory settings in the future.
