### ISSUE TITLE
Missing setup.py ?

### ISSUE THREAD

**Issue by pfdamasceno** [PennBBL/xcpEngine#203]
**Describe the bug**
pip install from github fails.

**Code needed for reproducing**
`pip install git+https://github.com/PennBBL/xcpEngine`

**Error message**
```FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/b6/s4w6qrrn7h98scj0yxzsm42m0000gn/T/pip-req-build-l6q296lg/setup.py'```

**Comment by a3sha2** [comment]
Your are trying to use python package : https://pypi.org/project/xcpengine-container
if you want to clone :  https://xcpengine.readthedocs.io/development.html

**Comment by pfdamasceno** [comment]
hi @a3sha2, my goal was to modify `xcpEngine` to use a custom atlas (issue #206) and then install this modified version, that's why I was looking into a pip install that I could add to my docker recipe.

You've fixed the issue above already so this issue is, at least for me, no longer a problem. Thanks.
