### ISSUE TITLE
Despiking parameters

### ISSUE THREAD

**Issue by araikes** [PennBBL/xcpEngine#214]
Quick question: for the 36p+despike, the design file has the following:
```
confound2_framewise[2]=fds:0.167,dv:2
```

I have two questions:

1. A lot of the examples on readthedocs also include the `rmss:` field for this line. Is it necessary or is it simply implied by the `fds` field and TR in the current versions?

1. What is the dv parameter and do I need to edit that? Is it just the number of frames over which to interpolate?

Thanks

**Comment by a3sha2** [comment]
Yes @araikes,
we removed `rmss` to avoid confusion with `fds`. Both are the same by defination. `dv` is  for is short form of D-VARS ( D referring to temporal derivative of timecourses, VARS referring to `rms` variance over voxels). You can look at this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3254728/

**Comment by araikes** [comment]
Hi @a3sha2, 
Thanks for clearing up point #1. I assumed that was the case.

For point #2, thanks for identifying that it was the dvars. I should've assumed that. In relationship to the despiking design file, does this value need to change as a function of TR? I ask because the example values in the design file are based on a TR of 3s (as identified in https://xcpengine.readthedocs.io/modules/regress.html#censoring) but I have a TR of 2s for my data and I want to make sure that I'm setting the parameters correctly.

Thanks

**Comment by a3sha2** [comment]
DVARS measures how much image intensity has changed from one frame to the next frame but FD measures relative displacement from one frame to the next. the `standardized` dvars usually less than 2 and a higher value of dvars usually cause by the movement (fd), so FD and DVARS are correlated to some extent (usually >0.4). There is no clear choice of dv threshold, it is sometime very important to look at the fmriprep carpet  plot. for example, maximum dv here is 1.17 for 3s TR 

<img width="586" alt="Screen Shot 2019-08-02 at 12 07 14 AM" src="https://user-images.githubusercontent.com/8614410/62351159-9bf53a80-b4b9-11e9-9ce7-f1dc62898f46.png">

 For 2s TR, I will suggest 2 or 1.5 dv

**Comment by araikes** [comment]
Thanks @a3sha2. 

After looking through my fMRIPrep outputs, 1.5 or 2 seemed to make sense.

I appreciate the input.
