### ISSUE TITLE
greymatter density refinement

### ISSUE THREAD

**Issue by a3sha2** [PennBBL/xcpEngine#237]

**Comment by a3sha2** [comment]
@sattertt  and @mattcieslak 
I discovered that antropos segmentation is not doing great for generating greymatter probability maps. The maximum value is around 0.85 for some subjects (instead of 1). WM and CSF are good. FSL FAST segmentation performed better. Do we replace it for now?

**Comment by a3sha2** [comment]
Normalization will take care of it for now

**Comment by sattertt** [comment]
Ok let’s discuss

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
