### ISSUE TITLE
Trouble Modeling Task-Driven Activity

### ISSUE THREAD

**Issue by abw58** [PennBBL/xcpEngine#249]
Hi All,

I posted a similar message on neurostars yesterday, but seems like this is the more active forum so re-posting here...

I am using xcpengine (singularity on google cloud platform) to process my results from fmriprep. Overall I’ve found it to be an excellent way to obtain ROI timecourses for subsequent network-based analyses, but I haven't quite figured out how to model task-driven activity as a confound.

From my understanding, I should create a 1D file with columns for each confound of interest and then 1s or 0s in each row (corresponding to each TR) for whether or not the condition of interest is present. There is no header to this file. The number of rows = num TRs. I can't attach the file type here, but can share over email if that would help.

I am using the default fc-aroma design file as is, except that I add in the below line in the confound module (2 in fc-aroma). 

confound2_custom[2]=/path/to/file

So far I have tried unsuccessfully to implement this for a single subject. xcpengine finishes without throwing an error, but the confound appears to be simply ignored.

I've thought of a few explanations for why this may be the case... I assume the path to the task confound should include the bind point, right? Do I need to somehow reference this confound in the regress (or another) module? Do I need to make any changes to the cohort file? And, finally, once I figure out how to make this work, I will need to reference a different task file for each subject, which I think should be done using {[sub]}, but I’m not completely sure on this either.

Any guidance on these matters would be much appreciated. Thank you!

Adam

**Comment by a3sha2** [comment]
Hi Adam, 
If you want to add custom regressors, you have to first convolve it with hemodynamic response function (HRF). The reason why it didnt work is base on the  mount and path to file. But you can add it to cohort file  like :: 
         `id0,id1,..,img,confound2_custom`
          `x,y,...,path/to/img,path/to/custom.`

**Comment by abw58** [comment]
Ah - thank you this is very helpful. To be clear, will xcp convolve the regressors if I add it to the cohort file, or is this an additional step I must perform before running xcp? 

-Adam

**Comment by a3sha2** [comment]
You have to do the convolution first . 

Az

**Comment by a3sha2** [comment]
you dont need this `confound2_custom[2]=${confound2_custom[sub]} `

which of the module did the error occur? it pass through `confound2`
can you share the log files pls?

**Comment by abw58** [comment]
I see - so I would just need to indicate confound2_custom in the cohort file? Do I leave confound2_custom blank in the design file (confound2_custom= )? Perhaps this is the cause of the error. The error occurred during the localiser, but it continued on and produced an output. I went back after posting this and realized that the error was still produced for a single subject, which I didn't realize until late yesterday.  I've attached the log. Thanks for your help. 

[singlesuberror.txt](https://github.com/PennBBL/xcpEngine/files/3796112/singlesuberror.txt)

**Comment by a3sha2** [comment]
@abw58  
the image is not not found, may be  you can share your cohort file 
and yes  set confound2_custom=

**Comment by abw58** [comment]
Hmm, okay. Here is the cohort file (I've saved it as an xlsx so that it can be attached - github does not accept csv attachments). I'm still a bit unclear on what xcpengine is doing, then, if it cannot find the image. Would that not just make it stop immediately? 
[gss_t1_cohort_file_mounted_confound_onesub.xlsx](https://github.com/PennBBL/xcpEngine/files/3798033/gss_t1_cohort_file_mounted_confound_onesub.xlsx)

**Comment by a3sha2** [comment]
it already indicated error during prestats . if you look at the log file, you see image missing [I] 
```···································································
· [D][/mnt/xcp_engine/xcp_design_files/fc-aroma_task_confound_onesub.dsn]
· [I][/tmp]
· [C][/mnt/xcp_engine/xcp_cohort_files/gss_t1_cohort_file_mounted_confound_onesub.csv]
· [O][/mnt/xcp_engine/output/task_test]
· [M][Executing serially]


I will advice you deleted previous runs and start again

**Comment by abw58** [comment]
So I tried from the beginning and received the same error. I'm at a bit of a loss as I just can't seem to figure out what is causing the problem at this point. It seems as though this is the exact spot where things are going wrong:

**Current processing step:
@1 Localising subject metadata...
····································································
· @1.1 [Parsing subject identifiers]
· @1.1a [Creating output directory]
· @1.1b [/mnt/xcp_engine/xcp_output/]
· @1.2 [Initialising space mapping]
· @1.3 [Initialising derivative maps]
· @1.4 [Initialising atlas system]
· @1.5 Ingress
· @1.5.1 [Native space: _anatomical]
· @1.5.2a [Standard space: MNI]
· @1.5.3a [Anatomical space: _anatomical]
source space map '' is not an image
· @1.5 [Priming analytic audit]
· @1.6 [Priming quality assessment]**

Again - do you know how it is that the pipeline still completes and gives me outputs? Just to be clear, I am not specifying any anatomical files in the cohort file. Is that okay? I just want to do the functional pipeline with fmriprep output.

**Comment by a3sha2** [comment]
show your code, how you run it on terminal like:

https://xcpengine.readthedocs.io/containers/index.html#using-xcpengine-with-singularity

**Comment by abw58** [comment]
Okay @a3sha2 - thanks for your patience thus far. Here is everything I have that I think would be needed to debug this. To be clear, my desire is to execute the functional pipeline from fmriprep 1.5.0 output. I am not interested in the anatomical pipeline. I am running this on the google cloud platform (with: sbatch run_xcpengine_task_serial.sh). Note that the results are the same regardless of whether I use the -r flag. Here is the code:

#!/bin/bash
#SBATCH --job-name="xcp"
#SBATCH --output="xcp.o%j"
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=30G
#SBATCH --mail-user=abw58@georgetown.edu
#SBATCH --mail-type=END,FAIL
singularity run \\
-B /home/abw58:/mnt /home/abw58/containers/xcpEngine.simg \\
-c /mnt/xcp_engine/xcp_cohort_files/sample_cohort_file_mounted.csv \\
-d /mnt/xcp_engine/xcp_design_files/fc-aroma_task.dsn \\
-o /mnt/xcp_engine/xcp_output \\
-i $TMPDIR \\
-t 2 \\

I am also attaching the csv cohort file (which I saved as a xlsx so that it can be attached here) as well as the txt log file.

The design file is below. This design file is identical to the fc-aroma design file on github with the following changes (which are bolded below): (1) I have changed the design path to where the design file is located locally (with the mnt), (2) I added the line confound2_custom[2]= and (3) I set all rerun = 1. It seems like it is missing anatomical information, but I am confused as to why.


###################################################################
# ANALYSIS VARIABLES
###################################################################

analysis=fc_$(whoami)
**design=/mnt/xcp_engine/xcp_design_files/fc-aroma_task.dsn**
sequence=anatomical
standard=MNI%2x2x2

###################################################################
# PIPELINE
###################################################################

pipeline=prestats,confound2,regress,fcon,reho,alff,roiquant,norm,qcfc

###################################################################
# 1 PRESTATS
###################################################################

prestats_rerun[1]=1
prestats_cleanup[1]=1
prestats_process[1]=FMP

###################################################################
# 2 CONFOUND2
###################################################################

confound2_rps[2]=0
confound2_rms[2]=0
confound2_wm[2]=1
confound2_csf[2]=1
confound2_gsr[2]=0
confound2_acompcor[2]=0
confound2_tcompcor[2]=0
confound2_aroma[2]=1
confound2_past[2]=0
confound2_dx[2]=0
confound2_sq[2]=1
confound2_censor[2]=0
confound2_censor_contig[2]=0
**confound2_custom[2]=**
**confound2_rerun[2]=1**
confound2_cleanup[2]=1

###################################################################
# 3  REGRESS
###################################################################

regress_tmpf[3]=butterworth
regress_hipass[3]=0.01
regress_lopass[3]=0.08
regress_tmpf_order[3]=1
regress_tmpf_pass[3]=2
regress_tmpf_ripple[3]=0.5
regress_tmpf_ripple2[3]=20
regress_dmdt[3]=2
regress_1ddt[3]=1
regress_smo[3]=6
regress_sptf[3]=susan
regress_usan[3]=default
regress_usan_space[3]=
**regress_rerun[3]=1**
regress_cleanup[3]=1
regress_process[3]=DMT-TMP-REG

###################################################################
# 4 FCON
###################################################################

fcon_atlas[4]=power264
fcon_metric[4]=corrcoef
fcon_thr[4]=N
fcon_window[4]=10
fcon_pad[4]=FALSE
**fcon_rerun[4]=1**
fcon_cleanup[4]=1

###################################################################
# 5 REHO
###################################################################

reho_nhood[5]=vertices
reho_roikw[5]=0 # does nothing at the moment
reho_sptf[5]=susan
reho_smo[5]=6
**reho_rerun[5]=1**
reho_cleanup[5]=1

###################################################################
# 6 ALFF
###################################################################

alff_hipass[6]=0.01
alff_lopass[6]=0.08
alff_sptf[6]=susan
alff_smo[6]=6
**alff_rerun[6]=1**
alff_cleanup[6]=1

###################################################################
# 7 ROIQUANT
###################################################################

roiquant_atlas[7]=power264
roiquant_globals[7]=1
roiquant_vol[7]=0
**roiquant_rerun[7]=1**
roiquant_cleanup[7]=1

###################################################################
# 8 NORM
###################################################################
norm_primary[8]=1
**norm_rerun[8]=1**
norm_cleanup[8]=1

##################################################################
# 9 QCFC
###################################################################
qcfc_atlas[9]=power264
qcfc_sig[9]=fdr
**qcfc_rerun[9]=1**
qcfc_cleanup[9]=1

[output.txt](https://github.com/PennBBL/xcpEngine/files/3805734/output.txt)
[sample_cohort_file_mounted.xlsx](https://github.com/PennBBL/xcpEngine/files/3805736/sample_cohort_file_mounted.xlsx)

**Comment by a3sha2** [comment]
look like you have everything set up very well. I willbe glad  if you can share  `/mnt/xcp_engine/xcp_output/sub-5.dsn`

everything works well except `roiquant` module. There is  problem with picking up `/mnt/xcp_engine/xcp_output/sub-5/sub-5_atlas/sub-5_power264.nii.gz`  I am sure you have the output and you look at the  ` /mnt/xcp_engine/xcp_output/sub-5_report.html` to verify

**Comment by abw58** [comment]
This just keeps getting more and more strange... I've attached the sub-5.dsn file, but there is a really bizarre issue with: /mnt/xcp_engine/xcp_output/sub-5/sub-5_atlas/sub-5_power264.nii.gz. For some reason, that is not a file but, instead, a folder (hence whey xcp engine cannot read it). If I cd to that folder, it takes me back to: /mnt/xcp_engine. This creates an infinite loop, because from there I can cd to xcp_output/sub-5/sub-5_atlas/sub-5_power264.nii.gz. 

[sub-5_dsn_toshare.txt](https://github.com/PennBBL/xcpEngine/files/3815476/sub-5_dsn_toshare.txt)

**Comment by abw58** [comment]
Hi @a3sha2 - thanks for your help with all of this. Since we are primarily interested in the ROI timecourse files, we are just going to proceed with the outputs that we do have from xcpengine. The roiquant module error hasn't been resolved, but we don't actually need what that gives us. If you make any progress on diagnosing the issue, please do let us know. 

Finally, I just want to confirm that we should be using the space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz file for the aroma design file and NOT the space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold.nii.gz file (we included aroma in fmriprep). Is that correct? 

Thanks again!

**Comment by a3sha2** [comment]
yes,
