### ISSUE TITLE
::XCP-WARNING: Functional connectome analysis has been requested,   but no network maps have been provided.

### ISSUE THREAD

**Issue by kimberlylray** [PennBBL/xcpEngine#250]
[xcpengine.o4607493.zip](https://github.com/PennBBL/xcpEngine/files/3791070/xcpengine.o4607493.zip)
Hello - thank you for developing and sharing this pipeline with us. 
I have resting state fMRI data that I have already run fMRIprep on. I am wanting to use XCPengine on our HPC (TACC) to remove confounds and then create a functional connectivity matrix based on the Schaefer400 parcellation. 

Any suggestions for trouble shooting the warning/error below on providing network maps would be much appreciated!
The entire output from XCP is provided in the zip file as well. 
Thanks for your time
Kim

**Describe the bug**
The job appears to 'completes', but the fcon directory is empty.  

**Cohort file**
Paste cohort file between the triple backticks
```
id0,id1,img
sub-12149,ses-02,sub-12149/ses-02/func/sub-12149_ses-02_task-REST_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
sub-12149,ses-03,sub-12149/ses-03/func/sub-12149_ses-03_task-REST_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
sub-12149,ses-01,sub-12149/ses-01/func/sub-12149_ses-01_task-REST_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
```

**Design File**
Paste your entire design (`.dsn`) file between the triple backticks
```
#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################


###################################################################
# This design file stores the values of all variables required to
# execute a complete neuroimage processing pipeline. You may
# execute the analysis specified in this design file by calling
# (in any v4 or higher bash terminal):
#
# xcpEngine -d <design> -c <cohort> -o <output> <options>
#
# Variables fall into five general categories:
# * ANALYSIS VARIABLES are used at all stages of this analysis.
# * PIPELINE specifies the modules that comprise the analysis.
# * MODULE VARIABLES are used during one stage of the analysis.
#                  These are typically array variables with array
#                  indices equal to the index of the module that
#                  calls them.
# * OUTPUT VARIABLES may be used at all stages of the analysis.
#                  These are typically array variables with array
#                  indices equal to the value of the primary
#                  subject identifier. They will appear only in
#                  localised design files.
###################################################################


###################################################################
# ANALYSIS VARIABLES
###################################################################

analysis=fc_$(whoami)
design=/Volumes/schnyer/R33ABM/XCP/fc-6p_scrub.dsn
standard=MNI%2x2x2
sequence=anatomical

###################################################################
# PIPELINE
###################################################################

pipeline=prestats,confound2,fcon

###################################################################
# 1 PRESTATS
###################################################################

prestats_rerun[1]=1
prestats_cleanup[1]=1
prestats_process[1]=FMP

###################################################################
# 2 CONFOUND2
###################################################################

confound2_rps[2]=1
confound2_rms[2]=0
confound2_wm[2]=1
confound2_csf[2]=1
confound2_gsr[2]=1 #this is actually scrubbing!!!! NOT gsr
confound2_acompcor[2]=0
confound2_tcompcor[2]=0
confound2_aroma[2]=0
confound2_past[2]=0
confound2_dx[2]=0
confound2_sq[2]=0
confound2_custom[2]=
confound2_censor[2]=0
confound2_censor_contig[2]=0
confound2_framewise[2]=
confound2_rerun[2]=1
confound2_cleanup[2]=1


###################################################################
# 4 FCON
###################################################################
#does this output r values or z scores? normalize or no?

fcon_atlas[4]=schaefer400
fcon_metric[4]=corrcoef
fcon_thr[4]=N #can take out in matlab later on
fcon_rerun[4]=1
fcon_cleanup[4]=1
```
**Error message**
Paste your error message between the backticks
```

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
#                                                                 #
#  ⊗               FUNCTIONAL CONNECTOME MODULE                ⊗  #
#                                                                 #
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################



[I][/scratch/05231/klray/KLR_local/xcp/sub-12149/ses-02/sub-12149_ses-02.nii.gz]
[O][/scratch/05231/klray/KLR_local/xcp/sub-12149/ses-02/fcon]

::XCP-WARNING: Functional connectome analysis has been requested,
  but no network maps have been provided.

  Skipping module


```

**Runtime Information**
I am using a singularity container that I updated this week. 

**Additional context**

**Comment by a3sha2** [comment]
the output of fcon is just correlation (r) not  zscores and not normalized 

change   `fcon_atlas[4]=schaefer400` to  `fcon_atlas[4]=schaefer400x17`  for 17-network and 
`fcon_atlas[4]=schaefer400x7`  for 7-network

**Comment by kimberlylray** [comment]
ah, thanks!  I was using a previous design matrix and did not know that the atlas naming had changed.  Can someone update this new naming on the "read the docs" ? 
I'll update my design file and rerun.  
I appreciate the quick feedback.

**Comment by kimberlylray** [comment]
Hi @a3sha2 , I've tried fcon_atlas[4]=schaefer400x17 and fcon_atlas[4]=all. 
I'm still getting the warning: 
::XCP-WARNING: Functional connectome analysis has been requested,
  but no network maps have been provided.

  Skipping module

Any other thoughts on why the icon module is being skipped? Thanks again!

**Comment by a3sha2** [comment]
sorry I didnt  look at the design file very well 
fcon should be [3] not [4]

**Comment by kimberlylray** [comment]
Ill fix that, thanks!

**Comment by kimberlylray** [comment]
@a3sha2 that works, thank you!

**Comment by kimberlylray** [comment]
@a3sha2  So sorry, it appears I spoke too soon!  
The fcon connectivity matrices are empty. 
 The atlases .nii images are in their respective 'atlas' directory
I've attached the output from processing multiple subjects 
[xcpengine.e4622113.zip](https://github.com/PennBBL/xcpEngine/files/3806258/xcpengine.e4622113.zip)

Any further troubleshooting would be greatly appreciated!

**Comment by a3sha2** [comment]
there is no regression module  in your design file. the bold must be regressed before computation of connectivity  


use this design file; 
```
#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################


###################################################################
# This design file stores the values of all variables required to
# execute a complete neuroimage processing pipeline. You may
# execute the analysis specified in this design file by calling
# (in any v4 or higher bash terminal):
#
# xcpEngine -d <design> -c <cohort> -o <output> <options>
#
# Variables fall into five general categories:
# * ANALYSIS VARIABLES are used at all stages of this analysis.
# * PIPELINE specifies the modules that comprise the analysis.
# * MODULE VARIABLES are used during one stage of the analysis.
#                  These are typically array variables with array
#                  indices equal to the index of the module that
#                  calls them.
# * OUTPUT VARIABLES may be used at all stages of the analysis.
#                  These are typically array variables with array
#                  indices equal to the value of the primary
#                  subject identifier. They will appear only in
#                  localised design files.
###################################################################


###################################################################
# ANALYSIS VARIABLES
###################################################################

analysis=fc_$(whoami)
design=/Volumes/schnyer/R33ABM/XCP/fc-6p_scrub.dsn
standard=MNI%2x2x2
sequence=anatomical

###################################################################
# PIPELINE
###################################################################

pipeline=prestats,confound2,fcon

###################################################################
# 1 PRESTATS
###################################################################

prestats_rerun[1]=1
prestats_cleanup[1]=1
prestats_process[1]=FMP

###################################################################
# 2 CONFOUND2
###################################################################

confound2_rps[2]=1
confound2_rms[2]=0
confound2_wm[2]=1
confound2_csf[2]=1
confound2_gsr[2]=1 #this is actually scrubbing!!!! NOT gsr
confound2_acompcor[2]=0
confound2_tcompcor[2]=0
confound2_aroma[2]=0
confound2_past[2]=0
confound2_dx[2]=0
confound2_sq[2]=0
confound2_custom[2]=
confound2_censor[2]=0
confound2_censor_contig[2]=0
confound2_framewise[2]=
confound2_rerun[2]=1
confound2_cleanup[2]=1


##################################################################
# 3  REGRESS
###################################################################

regress_tmpf[3]=butterworth
regress_hipass[3]=0.01
regress_lopass[3]=0.08
regress_tmpf_order[3]=1
regress_tmpf_pass[3]=2
regress_tmpf_ripple[3]=0.5
regress_tmpf_ripple2[3]=20
regress_dmdt[3]=2
regress_1ddt[3]=1
regress_smo[3]=6
regress_sptf[3]=susan
regress_usan[3]=default
regress_usan_space[3]=
regress_rerun[3]=0
regress_cleanup[3]=1
regress_process[3]=DMT-TMP-REG

###################################################################
# 4 FCON
###################################################################

fcon_atlas[4]=all
fcon_metric[4]=corrcoef
fcon_thr[4]=N
fcon_pad[4]=FALSE
fcon_rerun[4]=0
fcon_cleanup[4]=1 ```

**Comment by sattertt** [comment]
Just to chime in here, we in general we strongly recommend using one of the design files that is bundled with XCP.

**Comment by kimberlylray** [comment]
Thank you both  @a3sha2  and @sattertt for the (ongoing) feedback.  

I've tried a few different versions similar to your examples, and I also went ahead and used the fc-36p_scub.dsn from your GitHub.  Unfortunately, Im still getting stuck at the same point. 

When XCPengine gets to the Confound Regression Module, I get the error "Option not recognized"
The output says that the most recent command logged was: 
[tfilter -i /scratch/05231/klray/xcp_temp/sub-12149_ses-01-regress-278061577~TEMP~_DMT_REG.nii.gz -o /scratch/05231/klray/xcp_temp/sub-12149_ses-01-regress-278061577~TEMP~_DMT_REG_TMP.nii.gz -a 1.500000 -f butterworth -h 0.01 -l 0.08 -m /scratch/05231/klray/KLR_local/xcp/sub-12149/ses-01/prestats/sub-12149_ses-01_mask.nii.gz -r 1 -d 2 -1]
I've confirmed that both input files exist at those paths (**_DMN_REG.nii.gz and the **mask.nii.gz)

The output error file says: 
>> ${XCPEDIR}/utils/tfilter -i /scratch/05231/klray/xcp_temp/sub-12149_ses-01-regress-278061577~TEMP~_DMT_REG.nii.gz -o /scratch/05231/klray/xcp_temp/sub-12149_ses-01-regress-278061577~TEMP~_DMT_REG_TMP.nii.gz -a 1.500000 -f butterworth -h 0.01 -l 0.08 -m /scratch/05231/klray/KLR_local/xcp/sub-12149/ses-01/prestats/sub-12149_ses-01_mask.nii.gz -r 1 -d 2 -1
/xcpEngine/utils/tfilter: option requires an argument -- 1

Im not sure how to troubleshoot this issue. 
I've attached my output files, error files, logs, design file.  
Design: [fc-36p_scrub_original.dsn.zip](https://github.com/PennBBL/xcpEngine/files/3832121/fc-36p_scrub_original.dsn.zip)
Log: [fc_klray_201911082315_sub-12149_ses-01LOG-process.zip](https://github.com/PennBBL/xcpEngine/files/3832144/fc_klray_201911082315_sub-12149_ses-01LOG-process.zip)
Output file: [xcpengine.o4667512.zip](https://github.com/PennBBL/xcpEngine/files/3832136/xcpengine.o4667512.zip)
Error file: [xcpengine.e4667898.zip](https://github.com/PennBBL/xcpEngine/files/3832177/xcpengine.e4667898.zip)

Best- Kim

**Comment by a3sha2** [comment]
@kimberlylray 

pls sorry for late response, 
can you run it in new directory pls. if you look at https://github.com/PennBBL/xcpEngine/files/3832144/fc_klray_201911082315_sub-12149_ses-01LOG-process.zip there is conflict with previous runs.

**Comment by kimberlylray** [comment]
Thank you for your help in trouble shooting these errors.  After updating the Schaefer parcellation naming and inserting the missing, I was able to complete processing.
