### ISSUE TITLE
Can XCP input/output in MNI152NLin6Asym space?

### ISSUE THREAD

**Issue by alexlicohen** [PennBBL/xcpEngine#254]
Hi all,
I just discovered XCP and am very excited to use it instead of our post-fMRIprep 'custom' python scripts for fc analysis. HOWEVER, we do all of our analysis in the MNI152NLin6Asym 2x2x2 space/volume dimensions.

I do not see any documentation that indicates how to change the volume space XCP uses. Is it truly locked to the 2009 space? fMRIprep has spent a lot of time allowing for the creation and use of different volumen spaces (pediatric and/or aging analyses come to mind) and I'm hoping this is an easy flag in XCP.

Thanks!

**Comment by a3sha2** [comment]
Yes, can take any type of MNI template ( not only 2009 space), PNC and OASIS templates. We are working on taking the native space.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexlicohen** [comment]
This is great. To be clear, is XCP:
1) somehow agnostic to space/dimensions,
2) using the fmriprep tags to identify the correct segmentation for seeds, etc... 
3) or something else?

**Comment by a3sha2** [comment]
1. xcp takes any  dimension and cat take bold in t1w or template space ( all MNIs, PNC and OASIS templates).
2 it can handle any frmiprep tag  from 1.0 to 1.5x (current version)
