### ISSUE TITLE
How to update the newest version of the xcpengine-container ? 

### ISSUE THREAD

**Issue by BClab808** [PennBBL/xcpEngine#255]
Dear xcpengine developer

I have installed xcpengine-container with the following command 2 months ago ("pip install xcpengine-container"). After reading some issue reports in the GitHub website, I found xcpengine may have newer version but I don't know how to update the current version to the new one. Since I have limited background knowledge about docker, could you give me a hand to update this fantastic software ? Thank you !

**Comment by a3sha2** [comment]
Hi @BClab808 
You can uninstall and  reinstall again!
`pip uninstall xcpengine-container`
`pip install xcpengine-container`

**Comment by mattcieslak** [comment]
You can also specify an image to use with either `xcpengine-docker` or `xcpengine-singularity` using the `--image` argument
