### ISSUE TITLE
Concern regarding interpolate.py

### ISSUE THREAD

**Issue by trh3** [PennBBL/xcpEngine#264]
I have been working through the interpolate.py function to get a better understanding of how the spectral interpolation is performed, and I came across something that was a tad concerning. Specifically:

`parser.add_argument(
        '-t', '--tmask', action='store', required=True,
        help='[required]'
             '\nTemporal mask indicating whether each volume is seen or '
             '\nunseen. For instance, 1 could indicate that a volume '
             '\nshould be retained, while 0 would indicate that the '
             '\nvolume should be censored.')`

Implies that the scrubbing targets should be coded as 0 for scrub and 1 for good timepoint.

But line 84:
`t_obs=np.array(np.where(tmask==0))`
pulls out the 0 coded timepoints, then line 90
`seen_samples            =   (t_obs + 1) * t_rep`
indicates that 0 coded timepoints are to be considered as seen (which I assume means good timepoints).

All this is fine throughout the code until line 225-226:
`    img_data[np.ix_(bin_index,t_obs.ravel())] \
             = recon[:,t_obs.ravel()]`

**Which appears to replace only the good data with the interpolated data, rather than replace the bad data with the interpolated data.**

Is this the case? Or am I missing something entirely?

**Comment by a3sha2** [comment]
hi @trh3

Thank you  very much.  the parser arguments need to be updated. the volume to be scrubbed usually has 1 or 2 or 3, depending on the number  framewsie threshold  included (and failed)  in `confound2_framewise`. When a volume's  fds or rms or dv is greater than the threshold, tmask of that volume change to 1 or more depending on the number  of threshold the user set. Tmask indices with 0  are good volumes,

**Comment by trh3** [comment]
Thanks for clarifying @a3sha2. That also confirms my suspicion that at the end of the interpolation function, the bad volumes are not being interpolated over, rather the good volumes are. This would cause issues for any scans run through this function.

**Comment by a3sha2** [comment]
Thank you @trh3  https://github.com/PennBBL/xcpEngine/blob/master/utils/interpolate.py#L84
