### ISSUE TITLE
R Version in Singularity Image

### ISSUE THREAD

**Issue by shanaahall** [PennBBL/xcpEngine#265]
**Describe the bug**
I'm trying to get xcpEngine running with a singularity image for the first time and it's telling me that my version of R is wrong. It looks like it's using 3.3 from within the image but our server has version 3.6, which is also seems to be finding. Any help would be appreciated!

**Error message**
Paste your error message between the backticks
```
Error message
Checking general dependencies
····································································
· Version AFNI           AFNI_19.1.18 
· Version ANTs           3.0.0.0 
· Version FSL            fsl-5.0.10 
· Version C3D            1.1.0 
· Version JQ             jq-1.5
· Version XCP Engine     xcpEngine-v1.0
· R version              3.3.3 
· R scripting front-end  3.3.3 
Failed with error:  ‘cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer’
· [Dependencies check failed: RNifti]
· [Please add RNifti to your R installation]
· · RNifti version       
· · optparse version     
· · pracma version       
· · signal version       
[Aborting]
```

**Comment by a3sha2** [comment]
yes you need  to include `-e` or  `--cleanenv`  with singularity  to clean environment before running container. If it doesnt work, you can temporarily delete `.Rprofile` in your home directory
