### ISSUE TITLE
Design/Cohort files run into errors because xcpengine-docker binds them as read-only

### ISSUE THREAD

**Issue by AKSoo** [PennBBL/xcpEngine#268]
The python wrapper script cannot handle custom cohort and design files because it is binding them to the docker container as read-only (`ro`). This results in critical errors, especially for design file. Because `design` variable is not set to the docker design file path (`/design/design.dsn`), the localiser chokes, along with all the modules.

**Error message**
```
· [D][/design/design.dsn]
sed: cannot rename /design/sedYzmc5D: Device or resource busy
· [C][/cohort/cohort.csv]
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
Calls: write.table -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/cohort/cohort.csv': Read-only file system
Execution halted
```

```
/xcpEngine/core/parseArgsLocaliser: line 113: /xcpEngine/designs/fc-36p_despike-PNC-power264.dsn: No such file or directory
```

**Runtime Information**
xcpengine-docker

**Comment by a3sha2** [comment]
can you  let us know  how you  run it, I mean code
you can try  singularity as well

**Comment by AKSoo** [comment]
I just tested xcpengine-docker on tutorial dataset, as in the docs.

**Comment by AKSoo** [comment]
Specifying custom design file also causes this problem, and this actually breaks down the whole pipeline.

**Comment by AKSoo** [comment]
Not sure why this was closed. The python wrapper for docker is unusable with custom design files. The fix can be as simple as removing read-only tags for binds.

**Comment by bdeck8317** [comment]
> Not sure why this was closed. The python wrapper for docker is unusable with custom design files. The fix can be as simple as removing read-only tags for binds. The more robust solution would be working with a temporary copy of cohort/design files.

Also had this issue with the wrapper :(

**Comment by a3sha2** [comment]
can you post the command

**Comment by bdeck8317** [comment]
@a3sha2 ,

Here is my command:

xcpengine-docker \
  -d /Users/neurouser1/Documents/ADHD_200/xcpEngine/designs/fc-36p.dsn \
  -i /Users/neurouser1/Documents/ADHD_200/xcpEngine/xcpOutput \
  -c /Users/neurouser1/Documents/ADHD_200/xcpEngine/cohorts/WashU_cohort.csv \
  -o /Users/neurouser1/Documents/ADHD_200/xcpEngine/xcpOutput/WashU \
  -r /Users/neurouser1/Documents/ADHD_200/fmriprep_output/WashU/fmriprep \


Not a huge deal as you can just run via calling docker explicitly but good to note the issue.
