### ISSUE TITLE
Reserve variable for unprocessed/raw image

### ISSUE THREAD

**Issue by rciric** [PennBBL/xcpEngine#27]
Reserve a variable for the unprocessed/raw image. Currently, the variable img is used to reference both the unprocessed and the processed images; the rationale was that this variable would always point to the image that further processing steps should operate upon. However, this convention leaves the raw image inaccessible to downstream analyses.

**Comment by adrose** [comment]
Can't the raw image be accessed with ${img[${subjidx}]}? 

The strucQA module uses this assuming its the the raw input
