### ISSUE TITLE
xcpengine submitted on SLURM stopped during regressor module but reported completed 

### ISSUE THREAD

**Issue by Figsandcitrus** [PennBBL/xcpEngine#302]
Hi, 

I ran xcpengine on slurm and the output files show that it stopped running after before the regressor module, however, the job was reported as completed. I used the 36-p design file. 

I would like to know what could have cause this to happen.

**Comment by a3sha2** [comment]
can you post command, design file and error?

**Comment by Figsandcitrus** [comment]
likely related to specific nodes limitation on our end.
