### ISSUE TITLE
Error with design file 

### ISSUE THREAD

**Issue by nooshinjava** [PennBBL/xcpEngine#311]
I have a very basic question: when I run the xcpengine with docker I get the error as below: 
Constructing a pipeline based on user specifications
····································································
· [D][/design/design.dsn]
INFO: /root/matlab/startup.m does not exist ... creating
sed: couldn't edit /design/design.dsn: not a regular file
· [I][/scratch]
· [C][/cohort/cohort.csv]
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: read.csv -> read.table
Execution halted
· [O][/xcpOutput]
· [M][Executing serially]
····································································

**Comment by a3sha2** [comment]
there is sure docker or singularity  binding. can you  post the command ?

**Comment by nooshinjava** [comment]
Thanks! the problem resolved! I needed to change the paths and give permission to folders! 
Sorry!

**Comment by bwinsto2** [comment]
@nooshinjava I know this was a while ago but do you happen to remember what permissions/paths you needed to change? I'm running into the same problem, but I think all my permissions are open...

**Comment by nooshinjava** [comment]
Hi,

For me it wasn't a path permission problem. I found such command as below
which worked for me.

singularity run --cleanenv -B /XCP \
  /XCP/simg/xcpEngine-latest.simg \
  -d /XCP/designs/fc-36p_spkreg.dsn \
  -c /XCP/cohort_file/cohort.csv \
  -o /XCP/xcpOutput \
  -i /XCP/Work \
  -t 1
