### ISSUE TITLE
seed module or utils?

### ISSUE THREAD

**Issue by Figsandcitrus** [PennBBL/xcpEngine#326]
Hi,
my understanding is that the seed module is not recommended in pipeline but can be used, correct? the documentation is really poor and I guess outdated on this, would appreciate of gets updated with an example design file module. I didn't find it in any of recommended .dsn files, so I made mine(see relevant parts below). It makes the folders (seed>PCC) but only creates the *ts.1D file and none of the expected nii files. 

I have another question about how to use utils instead.
I was able to use in utils by using 
`singularity shell xcpEngine.simg`
and navigating to the utils and run it as
`Singularity> $XCPEDIR/utils/seedconnectivity -i xcp_output_files/sub-x/REST/run-01/regress/sub-x-01_residualised.nii.gz -s -10,-56,14 -r 7 -k 3 -o xcp_output_files/sub-x/REST/run-01/ -n RPCC -p `sub-x`

It works, but I don't know how to call it from a bash script. I guess is more a singularity question than xcpEngine. How do you call a standalone utility inside $XCPDIR without `Singularity shell`?

this is the dsn files.

```
pipeline=prestats,confound2,regress,fcon,reho,alff,dummy,seed,dummy,dummy
.
.
###################################################################
# 8 SEED added by Taha
###################################################################
seed_lib[8]=
seed_names[8]=PCC#LHP#RMC
seed_points[8]=-2,-62,24#-26,-20,-16#38,-22,50
seed_sptf[8]=susan
seed_smo[8]=4
seed_rerun[8]=1
seed_cleanup[8]=1
```

here is the error it gives during the execution of the pipeline:

> >> rln /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_referenceVolume.nii.gz /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/sub-x_rest_run-01_referenceVolume.nii.gz
>                              -   -   -
> >> 10-8-1
>                              -   -   -
> >> 10-1
> /xcpEngine/modules/seed/seed.mod: line 139: {seed_radius[cxt]}=5: command not found
> 
> 
> 
> Current processing step:
> @1 Spatially filtering image
> ····································································
> · @1.1 
> · @1.2 [Configuring SUSAN]
> · @1.4 
> · @1.6 
> · @1.10a [Filter: susan]
> · @1.10b [Smoothing kernel: 4 mm]
> · @1.11 
>                              -   -   -
> >> ${XCPEDIR}/utils/sfilter -i /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/sub-x_rest_run-01.nii.gz -o /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/sub-x_rest_run-01_sm4.nii.gz -s susan -k 4 -m /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_mask.nii.gz -u /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_referenceVolumeBrain.nii.gz
> · @u.3 
>                              -   -   -
> >> 4/2.35482004503
>                              -   -   -
> >> fslstats /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_referenceVolumeBrain.nii.gz -k /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_mask.nii.gz -p 50
>                              -   -   -
> >> 543.419312 *3/4
>                              -   -   -
> >> susan /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/sub-x_rest_run-01.nii.gz 407.56448400000000000000 1.69864360057672291981 3 1 1 /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_referenceVolumeBrain.nii.gz 407.56448400000000000000 /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/sub-x_rest_run-01_sm4.nii.gz
> Cannot open volume /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/sub-x_rest_run-01 for reading!
>                              -   -   -
> >> fslmaths /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/sub-x_rest_run-01_sm4.nii.gz -mul /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_mask.nii.gz /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/sub-x_rest_run-01_sm4.nii.gz
> Cannot open volume /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/sub-x_rest_run-01_sm4 for reading!
> ····································································
> Processing step complete:
> Spatially filtering image
> PCC#LHP#RMC -2,-62,24
> 
> 
> 
> Current processing step:
> @2 PCC
> ····································································
> · @2.2.1 
> · @2.3.1 Transforming coordinates to image
> · @2.3.2 
>                              -   -   -
> >> ${XCPEDIR}/utils/coor2nifti -i -2,-62,24 -t /xcpEngine/space/MNI/MNI-2x2x2.nii.gz -r -o /data/projects/fMRI/xcpEngine_files/xcp_temp/sub-x_rest_run-01-seed-388471852~TEMP~_coor_PCC.nii.gz
> ___________________________________________________________________
> Usage: coor2niffti -i <input> -o <output> <options>
> coor2nifti receives an octothorpe-delimited seed index
>   as input and creates a network map image as an output.
> Compulsory arguments:
>  -i : Input cordinates 
> 
>  -o : Output network
>       The path to the file where the output network will
>       be written.
> Optional arguments:
>  -r : Override radius. If this argument is passed to the
>       conversion script, then this radius will take the place
>       of any voxel radii defined in the seed library.
>  -t : Template image [default MNI 2mm]
>       The path to an image file that defines the coordinate
>       space used in the seed library.
>  -x : Trace
>       If this flag is set, then any commands called by the
>       coor2map routine will be explicitly printed to the
>       console or log.
>  -m : mm coordinates
>       If this flag is toggled, then input coordinates will be
>       treated as mm coordinates rather than voxel coordinates, and
>       the image qform and sform will be used to convert them to
>       voxel coordinates for seed generation.
>       
> · @2.3.3 
> Error in parse_args(OptionParser(option_list = option_list)) : 
>   Error in getopt(spec = spec, opt = args) : flag "e" requires an argument
> Execution halted
> · @2.3.4 
>                              -   -   -
> >> antsApplyTransforms -i /data/projects/fMRI/xcpEngine_files/xcp_temp/sub-x_rest_run-01-seed-388471852~TEMP~_coor1_PCC.nii.gz -r /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/prestats/sub-x_rest_run-01_referenceVolumeBrain.nii.gz -n Linear -o /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/PCC//sub-x_rest_run-01_connectivity_PCC_seed.nii.gz
>  file /data/projects/fMRI/xcpEngine_files/xcp_temp/sub-x_rest_run-01-seed-388471852~TEMP~_coor1_PCC.nii.gz does not exist . 
> terminate called after throwing an instance of 'itk::ExceptionObject'
>   what():  /tmp/ants/build/ITKv5/Modules/Core/Common/src/itkProcessObject.cxx:1412:
> itk::ERROR: ResampleImageFilter(0x560273975d10): Input Primary is required but not set.
> /xcpEngine/core/functions/exec_ants: line 1: 50860 Aborted                 (core dumped) ${ANTSPATH}/"${@}"
> · @3 Extracting mean timeseries
>                              -   -   -
> >> rm -f /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/PCC//sub-x_rest_run-01_connectivity_PCC_ts.1D
>                              -   -   -
> >> ${XCPEDIR}/utils/tswmean.R -i /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/sub-x_rest_run-01.nii.gz -r /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/seed/PCC//sub-x_rest_run-01_connectivity_PCC_seed.nii.gz
> Error in dumpNifti(impath) : 
>   Failed to read image from path /data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/sub-x_rest_run-01.nii.gz
> Calls: dumpNifti -> .Call
> In addition: Warning message:
> In dumpNifti(impath) :
>   nifti_image_read: failed to find header file for '/data/projects/fMRI/xcpEngine_files/xcp_output_files/sub-x/rest/run-01/sub-x_rest_run-01.nii.gz'
> Execution halted
> · @4 SCA at smoothness 0 mm
>                              -   -   -
> >> rm -f PCC_sm0[8]
>

**Comment by a3sha2** [comment]
you can call it from bash script like this 

``` singularity exec xcpsingularityimage.simg   /utils/seedconnectivity  {every other daetails}```

the main issue is that you didnt include radius for the point  to create a seed mask. I have set radius to default 5mm, You can include it in the design file as `seed_radius[8]=X`

**Comment by Figsandcitrus** [comment]
Thank you a3sha2. the bash command line for utils works for me. Not sure if you can just pick an atlas ROI from xcp_atlas and run it  as seed. 

the module still doesn't work. could it be .nii vs .nii.gz format? either way I think the utils method is better, as one doesn't need to make multiple dsn for each new seed analysis
Thanks!

**Comment by a3sha2** [comment]
Yes, instead of points, atlas roi or mask can be used --s /path/to/mask
