### ISSUE TITLE
some minor "bugs" 

### ISSUE THREAD

**Issue by dominikkraft** [PennBBL/xcpEngine#339]
Hi all,

I´m rather new to XPC and I´m currently trying to set up the 36p-despike.dsn with slightly different parameters (i.e., I´m mostly interested in denoising and QC). I get some "warnings" or "error massages" troughout runtime, I think those are rather minor issues, but would be happy to get feedback on how to avoid them or just to understand them correctly! Thanks in advance!

I´m running XCP (Version 1.2.0) with singularity using ""unset PYTHONPATH; singularity run --cleanenv "" before my actual command. 

**Describe the bug**
XPC did not crash, just some minor "bugs" that I´d like to understand :) 

**Cohort file**
Paste cohort file between the triple backticks
```
id0,img
sub-aam063,/data/hippocampus/FLEX/FLEX_rest_FINAL/BIDS/derivatives/fmriprep/sub-aam063/func/sub-aam063_task-rest_space-T1w_desc-preproc_bold.nii.gz
```

**Design File**
Paste your entire design (`.dsn`) file between the triple backticks
```
#!/usr/bin/env bash

###################################################################
#  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  ⊗  #
###################################################################


###################################################################
# This design file stores the values of all variables required to
# execute a complete neuroimage processing pipeline. You may
# execute the analysis specified in this design file by calling
# (in any v4 or higher bash terminal):
#
# xcpEngine -d <design> -c <cohort> -o <output> <options>
#
# Variables fall into five general categories:
# * ANALYSIS VARIABLES are used at all stages of this analysis.
# * PIPELINE specifies the modules that comprise the analysis.
# * MODULE VARIABLES are used during one stage of the analysis.
#                  These are typically array variables with array
#                  indices equal to the index of the module that
#                  calls them.
# * OUTPUT VARIABLES may be used at all stages of the analysis.
#                  These are typically array variables with array
#                  indices equal to the value of the primary
#                  subject identifier. They will appear only in
#                  localised design files.
###################################################################


###################################################################
# ANALYSIS VARIABLES
###################################################################

analysis=fc_$(whoami)
design=/data/hippocampus/FLEX/FLEX_rest_FINAL/BIDS/fc-36p_despike.dsn
sequence=anatomical
standard=MNI%1x1x1 #### 2x2x2

###################################################################
# PIPELINE
###################################################################

pipeline=prestats,confound2,regress,fcon,qcfc

###################################################################
# 1 PRESTATS
###################################################################

### input bold signal is from fmriprep ### 
prestats_process[1]=FMP

###################################################################
# 2 CONFOUND2
###################################################################

confound2_rps[2]=1
confound2_rms[2]=0
confound2_wm[2]=1
confound2_csf[2]=1
confound2_gsr[2]=1
confound2_acompcor[2]=0
confound2_tcompcor[2]=0
confound2_aroma[2]=0
confound2_past[2]=0
confound2_dx[2]=1
confound2_sq[2]=2
confound2_custom[2]=
confound2_censor[2]=0
confound2_framewise[2]=fds:0.37,dv:2 ### 0.37 * 0,675 = 2,5 mm etwa
confound2_censor_contig[2]=0
confound2_rerun[2]=0 #### skip processing  it outputs are available
confound2_cleanup[2]=1

###################################################################
# 3  REGRESS
###################################################################

regress_tmpf[3]=butterworth #### filters data and  nuisance regressors ###
regress_hipass[3]=0.01
regress_lopass[3]=0.08
regress_tmpf_order[3]=1 ###first order?? ## 
regress_tmpf_pass[3]=2
regress_tmpf_ripple[3]=0.5 ##not relevant for butter##
regress_tmpf_ripple2[3]=20
regress_dmdt[3]=2 ##demean & detrend
regress_1ddt[3]=1 ## demean detrend 1d  timeseries? ##
regress_smo[3]=0
regress_sptf[3]=none
#regress_usan[3]=default 
#regress_usan_space[3]=
regress_rerun[3]=0
regress_cleanup[3]=1
regress_process[3]=DMT-DSP-TMP-REG

###################################################################
# 4 FCON
###################################################################

fcon_atlas[4]=schaefer
fcon_metric[4]=corrcoef
fcon_thr[4]=N
fcon_rerun[4]=0
fcon_cleanup[4]=1

###################################################################
# 5 REHO
###################################################################

reho_nhood[5]=vertices
reho_roikw[5]=0 # does nothing at the moment
reho_sptf[5]=susan
reho_smo[5]=6
reho_rerun[5]=0
reho_cleanup[5]=1

###################################################################
# 6 ALFF
###################################################################

alff_hipass[6]=0.01
alff_lopass[6]=0.08
alff_sptf[6]=susan
alff_smo[6]=6
alff_rerun[6]=0
alff_cleanup[6]=1

###################################################################
# 7 ROIQUANT
###################################################################

roiquant_atlas[7]=all
roiquant_globals[7]=1
roiquant_vol[7]=0
roiquant_rerun[7]=0
roiquant_cleanup[7]=1

###################################################################
# 8 NORM
###################################################################
norm_primary[8]=1
norm_rerun[8]=0
norm_cleanup[8]=1

##################################################################
# 9 QCFC
###################################################################
qcfc_atlas[9]=schaefer
qcfc_sig[9]=fdr
#qcfc_confmat[9]=/data/hippocampus/FLEX/FLEX_rest_FINAL/BIDS/confounds_xpg.csv
#qcfc_conformula[9]=age+factor(gender)
qcfc_rerun[9]=0
qcfc_cleanup[9]=1




```
**Error message**
Paste your error message between the backticks
```
see additional context
```

**Runtime Information**
singularity 

**Additional context**
I attached my logfile.

1) I get a lot of: 
/xcpEngine/core/functions/rerun: line 3: ((: == 1 : syntax error: operand expected (error token is "== 1 ") errors, I think this has already been reported here: https://github.com/PennBBL/xcpEngine/issues/215

2) Current processing step:
Spatially filtering image
····································································
/xcpEngine/modules/regress/regress.mod: line 478: ${1wtotemp2}: bad substitution
····································································
Processing step complete:
Spatially filtering image

--> This occurs despite smoothing is turned of in my design file 

3) Current processing step:
Estimating loss of temporal degrees of freedom
····································································
· 36 nuisance parameters regressed
· 0 volumes censored
· 0 number of spikes FD
· 0 number of spikes FD
/xcpEngine/modules/qcfc/qcfc.mod: line 263: nSpikesDV: command not found
· Total lost tDOF: 36
····································································
--> tbh, I can´t get my head around this one, atm 

4) Current processing step:
Preparing summary graphics
····································································
· Acquiring arguments
· Generating visuals
Error: Unequal parameter lengths: x (4), label (3)
Execution halted
····································································
Processing step complete:
Preparing summary graphics

--> I think this has been reported here: https://github.com/PennBBL/xcpEngine/issues/327, using --cleanenv however does not seem to solve the issue

5) Module complete
generating report
/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/xcpEngine/core/report.py", line 317, in <module>
    atlaslist.remove('global')
ValueError: list.remove(x): x not in list
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

It would be great if someone could give me feedback on these issues, I feel like non of these is really bad, but it would be great to understand what is exactly going on here. Following this, just to get it right, the main outcome from the regress module is the __residualized.nii.gz right? This would be the one for further analyses? I was confused because in subject/ there is also a subject_nii.gz file which seems to pretty much the same as the subject_residualized (i.e., when extracting signal from a ROI and plot the time series) 

Thank you very much in advance and also for this neat tool!

Best,
Dominik

[sub-aam063_logxpc.pdf](https://github.com/PennBBL/xcpEngine/files/4724319/sub-aam063_logxpc.pdf)

**Comment by a3sha2** [comment]
@dominikkraft 
Sorry for late response. You dont have to worry with these errors, most of the errors are from the design file, due to addition of some characters. let me know if you have correct output in qcfc
