### ISSUE TITLE
an issue with acompcor_select.py in the container

### ISSUE THREAD

**Issue by JulioAPeraza** [PennBBL/xcpEngine#345]
Dear developers,

Thank you for creating and maintaining this tool. It is awesome!

I am rather new using it. I am using the latest version: `1.2.1`.

I created the image with `singularity build xcpengine-1.2.1.sif docker://pennbbl/xcpengine:1.2.1`

It seems that the function `acompcor_select.py` is not working from the container. Instead of saving the first 5 components of CSF and WM, it is saving random components of the same `desc-confounds_regressors.tsv` file.

The code looks fine. I tested it outside the container and works. I think the issue is with the container since I ran it using `singularity shell --cleanenv xcpengine-1.2.1.sif` and it also produced those random results every time I ran it. I also ran it with docker and got the same random a_comp_cor columns.

`
docker run --rm -it -v /Users/jperaza/Desktop:/data --entrypoint /xcpEngine/utils/acompcor_select.py pennbbl/xcpengine:1.2.1 -j /data/sub-01_ses-01_task-rest_desc-confounds_regressors.json -c /data/sub-01_ses-01_task-rest_desc-confounds_regressors.tsv -o /data/test.txt
`

I wonder if I am doing something wrong in my call to the container. Is this working for you with the container from your side?

Thank you for your help!

**Comment by a3sha2** [comment]
Hi @JulioAPeraza 
you can read more about it here  https://github.com/PennBBL/xcpEngine/issues/334.  in the confound regressors, the components are not being arranged in order of  `VarianceExplained`. it is just random ordering. You can check *desc-confounds_regressors.json to see the detail.  it is better is better to select the  first 5 components by VarianceExplained because the arrangement in the .tsv file is not in order. You can plot one subject to see.

**Comment by JulioAPeraza** [comment]
Hi @a3sha2 

Thank you so much. I checked issue #334. I am using the latest version of both fMRIPrep and xcpEngine.

I believed the component are organized according to their singular value (https://fmriprep.org/en/stable/outputs.html#confounds).

The function `acompcor_select.py` is ok, the issue from my side is only happening inside the container.

I ran it outside the container 
`
python acompcor_select.py -j /Users/jperaza/Desktop/sub-01_ses-01_task-rest_desc-confounds_regressors.json -c /Users/jperaza/Desktop/sub-01_ses-01_task-rest_desc-confounds_regressors.tsv -o /Users/jperaza/Desktop/test-local.txt
`
and it selected the right components. For example, for CSF: `a_comp_cor_300`, `a_comp_cor_301`, `a_comp_cor_302`, `a_comp_cor_303`, `a_comp_cor_304`, which indeed explained the 50% of the variance since `CumulativeVarianceExplained(a_comp_cor_304) > 0.5`

But when I ran it using the same data but inside the container, 
`
docker run --rm -it -v /Users/jperaza/Desktop:/data --entrypoint /xcpEngine/utils/acompcor_select.py pennbbl/xcpengine:1.2.1 -j /data/sub-01_ses-01_task-rest_desc-confounds_regressors.json -c /sub-01_ses-01_task-rest_desc-confounds_regressors.tsv -o /data/test-container.txt
`
it selected different random components every time I ran it. For example, 
Docker run 1 for CSF: `a_comp_cor_329`, `a_comp_cor_342`, `a_comp_cor_319`, `a_comp_cor_386`, `a_comp_cor_435`; 
Docker run 2 for CSF: `a_comp_cor_422`, `a_comp_cor_312`, `a_comp_cor_338`, `a_comp_cor_331`, `a_comp_cor_337`

I do not have any experience with docker/singularity, so I do not know why this function is having odd behavior inside the container.  I was wondering if this function works for you inside the container?

Thank you for your time!

**Comment by JulioAPeraza** [comment]
I have run the function `acompcor_select.py` outside the container but with the python version (3.5.3) of xcpEngine's container, and it did not work. 
The function did work with the python version (3.7.1) of fMRIPrep.

**Comment by a3sha2** [comment]
Thank you Julio, I am looking at now to see what went wrong

**Comment by a3sha2** [comment]
@JulioAPeraza 

Pls can you pull for new docker image (pennbbl/xcpengine:latest or pennbbl/xcpengine:1.2.1) and let me know. 
thanks 
nice to meet you neurohackedemy 2019

**Comment by JulioAPeraza** [comment]
Hi @a3sha2, 
The function is working. Thank you so much for fixing this so quickly.
