### ISSUE TITLE
Build in a minimal structural processing pipeline

### ISSUE THREAD

**Issue by adrose** [PennBBL/xcpEngine#37]
As not all groups will be interested in running the full ANTsCT pipeline - the antsCT module should be able to run just BE and registration as this will produce all of the required inputs for norm to run.

**Comment by sattertt** [comment]
Goal is to have by next fri 9/22 have compatibility with CBICA output ready.  Need to go to cbica meeting and say "it's done."

**Comment by adrose** [comment]
This will just need to call this ants script here: 

https://github.com/ANTsX/ANTs/blob/master/Scripts/antsRegistrationSyN.sh

**Comment by adrose** [comment]
The way I had built the struc module - I had built in a specific BE section, just needs a registration and segmentation - which I think @rciric has already built in
