### ISSUE TITLE
confound2/mc relRMS.1D == fd.1D

### ISSUE THREAD

**Issue by dominikkraft** [PennBBL/xcpEngine#397]
Within the confound module, it appears that `utils/generate_confmat.R` reads the framewise displacement from the fmriprep confound table and saves it as `subject_relRMS.1D`. But I think this should refer to Jenkinsons RMS displacement. 

Code chunk:
````
{XCPEDIR}/utils/generate_confmat.R -i /data/hippocampus/FLEX/FLEX_rest_FINAL/BIDS/test_denoised/sub-vfo297/prestats/sub-vfo297_fmriconf.tsv -j fd -o /data/hippocampus/FLEX/FLEX_rest_FINAL/BIDS/test_denoised/sub-vfo297/confound2/mc/sub-vfo297_relRMS.1D
````

The FD **_fd.1D** calculated within `/utils/fd.R` appears to be identical to **RMS.1D** , too.

Given that fmriprep now outputs **rmsd** one could integrate it here (under RMS.1D) and avoid confusion and allow for better stream lining with fmriprep versions 20.X.X and newer. 

Best,
Dominik

**Comment by a3sha2** [comment]
thank you @dominikkraft
