### ISSUE TITLE
confound2_custom for estimates of task-driven activity

### ISSUE THREAD

**Issue by Figsandcitrus** [PennBBL/xcpEngine#400]
I want to regress-out a task estimate as a custom confound.  ( https://xcpengine.readthedocs.io/modules/confound.html#confound2-custom )

I believe I should change the following in my dsn file:
`confound2_custom[cxt]=
`

Is there a way to add .1D estimates of task-driven activity files in cohort file? Currently I don't see any additional file in the custom2 folder when I do the following.

Cohort file example
```
id0, id1,img,confound2_custom
sub-01,run-01,/path/to/sub-01.nii.gz,/path/to/sub-01.1D
```

**Design File**
This is what I assumed I should do:
Paste your entire design (`.dsn`) file between the triple backticks
```

confound2_custom[cxt]= 1

```
**Runtime Information**
running on Singularity tried both locally and on HCP

**Additional context**
Further explanation for this part of the documentation would help
https://xcpengine.readthedocs.io/modules/confound.html#confound2-custom

**Comment by a3sha2** [comment]
You can add it in cohort file, that is good. 

This is not necessary anymore `confound2_custom[cxt]= 1`, just leave it empty

To verify that the  custom time series are added to nuisance regressors or not, check this file `*_modelParameterCount.txt` in confound2 to see number of nuisance regressors. If you are regressing 36p (36 motion parameters) , the modelParameterCount will be 36+N where N is number of column of custom regressors you added.

**Comment by Figsandcitrus** [comment]
Thanks. Yes it seems it changed it to 37 from 36. There is little effect on the regress timecourse and the fcon module results, so I guess I have to review how I make my 1D file for the task, I created it in SPM12. Does it have to be in FEAT? appreciate if you can update the documentation and answer this question.

I can close this issue it was a very helpful answer!

**Comment by a3sha2** [comment]
It is not necessary to be in FEAT format but the time series has to be convolved  with hemodynamic  response function (HRF).
Thank you, documentation will be updated!
