### ISSUE TITLE
xcpEngine v1.2.3 incorrectly shows "v1.2.1" as ouput of "xcpEngine -v"

### ISSUE THREAD

**Issue by ulloaa** [PennBBL/xcpEngine#416]
I pulled xcpEngine v1.2.3 from docker hub (using singularity pull) but it shows an incorrect version number.

```
Singularity xcpengine_latest.sif:~> xcpEngine -v
Received options: -v
xcpEngine-v1.2.1
```

When I checked at the current repo it looks like there is an incorrect version number at:
https://github.com/PennBBL/xcpEngine/blob/master/core/VERSION

**Comment by llevitis** [comment]
Hi, following up on this as this - this is one of the errors that I'm getting using that same container: 

```
Current processing step:
getting data from fmriprep directory
····································································
cp: cannot stat '/data/DNU/liza/data/XXY/Nifti/derivatives/fmriprep/sub-NDARINV8XENUGU9/ses-v01/func/sub-NDARINV8XENUGU9_ses-v01_task-rest_desc-confounds_regressors.tsv': No such file or directory
```


I thought that this was resolved with v1.2.3 (to be compatible with the latest fMRIPrep naming conventions), but I noticed that the actual version of the aforementioned container is still 1.2.1. 

Thank you for your help!

**Comment by a3sha2** [comment]
Hi @ulloaa and @llevitis 
Thank you very much!
@ulloaa , the version as reported on the docker image is correct. We have made correction in the script 
@llevitis, yes v1.2.3 is compatible with LTS , I expect the current docker or singularity image to pick `*task-rest_desc-confounds_timeseries.tsv`  not  `*regressors.tsv`

**Comment by llevitis** [comment]
This issue has been resolved once the new container was pulled. Thank you!
