### ISSUE TITLE
Residualized gifti outputs in the other spaces such as fsaverage5

### ISSUE THREAD

**Issue by YukiSakai1209** [PennBBL/xcpEngine#419]
@a3sha2
When I see regress.mod ( https://github.com/PennBBL/xcpEngine/blob/3fca3eb6eada4440618866fd25e0c5510012b1f8/modules/regress/regress.mod ), it seems that we can get the residualized gifti outputs only for the gifti in fsnative space. When we want to get the residualized gifti outputs in the other spaces such as fsaverage5, how can we do it? Since fmriprep has many other kinds of output spaces, it will be much more useful if we can get them.

It's a very similar problem, but for cifti output, if there are different densities of output (i.e., 91k and 170k), I think one of them will be overwritten. How can I get both outputs?

**Comment by a3sha2** [comment]
@YukiSakai1209  
I will look at it quickly and get back to you

**Comment by YukiSakai1209** [comment]
@a3sha2
Thank you for your quick response.

**Comment by a3sha2** [comment]
pls pull for new docker singularity  image pls `pennbbl/xcpengine:latest` 
let me know if works for you or not pls

**Comment by YukiSakai1209** [comment]
@a3sha2
Thank you very much.
I'll pull docker image pennbbl/xcpengine:latest and try it.

**Comment by YukiSakai1209** [comment]
@a3sha2
By the way, as I mentioned in # 411 ( https://github.com/PennBBL/xcpEngine/issues/411 ), surface processing will not work when we add ‘despike’.
How can we get the residualized cifti/gifti outputs when we use fc-36p_despike.dsn?

**Comment by YukiSakai1209** [comment]
@a3sha2
Although I have not finished the whole analysis steps, I confirmed the residualized cifti/gifti outputs (e.g., cifti: den-91k; gifti: fsaverage5 and fsnative).
Although I saw one carpet plot (.svg) for two gifti (fsaverage5 and fsnative), this may be the behavior you are expecting if you are outputting at the downsampled resolution. Is my understanding correct?
Thank you.

**Comment by a3sha2** [comment]
yes, thank you @YukiSakai1209
