### ISSUE TITLE
Is there a feature to censor additional volumes that are adjacent to outlier volumes?

### ISSUE THREAD

**Issue by chidiugonna** [PennBBL/xcpEngine#431]
Hi,
I would like to additionally censor volumes that precede or succeed a volume that exceeds the FD threshold. Is this possible to do "out of the box" with xcpEngine. I was not able to identify any means of doing this in the documentation.

To illustrate what i mean - in a toy example I have 10 volumes in a resting state time series one of which (volume 6) exceeds my FD threshold. Ordinarily I would censor just volume 6 but I would also like to censor volumes 5 and 7. 

Thank you
Chidi

**Comment by a3sha2** [comment]
Hi Chidi, 
no, that is not implemented

**Comment by chidiugonna** [comment]
Hi Azeez,
Thanks for the quick reply and thank you for all the hard work you and the team have put into XCP. It is much appreciated. If you think this is something that would have wider take-up then perhaps we could look into it at a later date. In the meantime I think this can be closed.
All the best
Chidi
