### ISSUE TITLE
RERUN failures

### ISSUE THREAD

**Issue by rciric** [PennBBL/xcpEngine#52]
This thread will identify any code blocks where rerun fails or is not used to effect.

* Slicewise renderings of registration quality are computed regardless of whether they already exist, as are coregistration quality metrics. There is no need to recompute these if coregistration is not recomputed.
* The network module reruns the roi2ts, ts2adjmat, adjmat2pajek, withinBetween commands regardless of whether the output exists. Await the resolution of #46 before tackling this.

**Comment by mattcieslak** [comment]
coreg is removed
