### ISSUE TITLE
$ANTSPATH/../ANTS-build/ProjectSOurceVersionVars.cmake file doesn't exists 

### ISSUE THREAD

**Issue by irem-a** [PennBBL/xcpEngine#63]
the xcpEngine can't find the ANTS version and fails even though I have ANTS installed.

**Comment by adrose** [comment]
@irem-a, could you send the output from running

`ls $ANTSPATH/../`

Thanks!

**Comment by irem-a** [comment]
ANTS-build/
ANTS-prefix/
bin/
CMakeCache.txt
CMakeFiles/
cmake_install.cmake
CPackConfig.cmake
CPackSourceConfig.cmake
CTestTestfile.cmake
DartConfiguration.tcl
ITKv4/
ITKv4-build/
ITKv4-install/
ITKv4-prefix/
lib/
Makefile
Testing/

**Comment by adrose** [comment]
Hey @rciric would you be opposed to changing 
`ver_ANTS=$(grep` -i _GIT_VERSION_HASH ${ANTSPATH}/../ANTS-build/ProjectSourceVersionVars.cmake 2>/dev/null|cut -d'"' -f2)` in the checkDependenciesXCP 
to 
`ver_ANTS=$(grep -ir _GIT_VERSION_HASH ${ANTSPATH}/../ANTS-build/* 2>/dev/null|cut -d'"' -f2)`

I actually don't know if this is a perfect solution but if there is a file with a field name _GIT_VERSION_HASH this'll find it w/o looking into a specific file, which as we found today not everyone has.

**Comment by rciric** [comment]
Thanks for drawing our attention to this issue, @irem-a! 

I'm going to implement the following changes in accordance with your report:

* As suggested by @adrose, I'll implement a more generic search for the version file.
* The version check will become independent of the dependency check. When the processing system detects that a dependency is installed but is unable to identify its version, the system will log the version as `unknown` and will provide a warning. However, the system will no longer abort.
