### ISSUE TITLE
ANTsR → oro.nifti

### ISSUE THREAD

**Issue by rciric** [PennBBL/xcpEngine#69]
- I am opening this issue to consider the feasibility of phasing out ANTsR in favour of an alternative NIfTI interface for R. One possibility is `oro.nifti`, which was previously used by Angel Garcia for his `voxel` package.
- The motivations for dropping ANTsR are threefold.
- First, ANTsR is not hosted on CRAN, and installation is consequently less straightforward than it is for most R packages.
- Second, ANTsR development is rapid, and backwards compatibility is not guaranteed. This has already become a major problem with collaborations -- a number of our funded collaborators are unable to use v0.5.x out of the box because ANTsR's matrix2timeseries function no longer accepts the same inputs that it did when the v0.5.x R utils were written.
- Third, ANTsR's ability to interface with NIfTI headers is not intuitive (although I write from the perspective of a person biased by the world of SPM). Rather than assigning values to header fields, ANTsR often copies header information from other images.
- To assess the feasibility of this change,  the first step will be creating an inventory of utils that use ANTsR.

_Sent from my Lge LG-TP260 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rciric** [comment]
The initial inventory reveals that a grand total of 23 utilities use `ANTsR`:

```
utils/1dGenfilter.R
utils/ablateAndImputeImage.R
utils/censor.R
utils/cmass.R
utils/com2map.R
utils/coverMask.R
utils/dmdt.R
utils/dvars.R
utils/extendMaskInferior.R
utils/func2map.R
utils/genfilter.R
utils/interpolate.R
utils/maskOverlap.R
utils/nodeCoverage.R
utils/renormalisePriorsPreserveCSF.R
utils/roi2ts.R
utils/stick2lm.R
utils/strucQA.R
utils/telescope.R
utils/tswmean.R
utils/unique.R
utils/val2mask.R
utils/voxts.R
```

Of these, nearly all use `ANTsR` for the purpose of reading and writing images rather than importing `ANTsR`-specific functionality.

**Comment by adrose** [comment]
Might want to double check this list. cortCon.R isn't on it - I can update the utils I wrote though

**Comment by rciric** [comment]
Sorry -- forgot to check the ones that aren't yet imported into `ACCELERATOR`! I believe that should be only `cortCon.R`, though.
