### ISSUE TITLE
ROI-wise quantification: update for structural processing

### ISSUE THREAD

**Issue by rciric** [PennBBL/xcpEngine#7]
Update the roiquant module to:
* Allow registrations into structural space
* Allow ROI-wise volume quantification
* Ensure improper subject-level directories are not generated

**Comment by adrose** [comment]
Still seeing this error after pulling latest roiquant module:

"Image Exception : #22 :: ERROR: Could not open image /data/joy/BBL/studies/pnc/processedData/structural/structuralModuleTest/100031/*x3818/100031_*x3818_roi/100031_*x3818_JLFintersect"
