### ISSUE TITLE
Group directory

### ISSUE THREAD

**Issue by lrnbeard** [PennBBL/xcpEngine#89]
The pipeline currently outputs a 'group' folder along with the processed data.

**Comment by rciric** [comment]
Hello @lrnbeard @sattertt ,

* The `group` directory is intended to provide an all-purpose site for storing processing outputs collated across all subjects, as well as any outputs of processing steps performed at the group level (for instance, pipeline benchmarks such as QC-FC computations).
* One possibility for handling this in the future would be introducing the ability to specify a group-level output directory as an additional argument to the engine script.
* In this case, `group` would be the default group-level output path and could be overridden if the optional argument is provided as a valid path on the file system.

Alternative suggestions are of course welcome.

**Comment by sattertt** [comment]
yes, personally would prefer this be in a specified output path, not in the main subject output root dir

On Oct 3, 2017, at 2:10 PM, Rastko Ćirić <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @lrnbeard<https://github.com/lrnbeard> @sattertt<https://github.com/sattertt> ,

  *   The group directory is intended to provide an all-purpose site for storing processing outputs collated across all subjects, as well as any outputs of processing steps performed at the group level (for instance, pipeline benchmarks such as QC-FC computations).
  *   One possibility for handling this in the future would be introducing the ability to specify a group-level output directory as an additional argument to the engine script.
  *   In this case, group would be the default group-level output path and could be overridden if the optional argument is provided as a valid path on the file system.

Alternative suggestions are of course welcome.
