### ISSUE TITLE
3dpc interface

### ISSUE THREAD

**Issue by rciric** [PennBBL/xcpEngine#97]
The name of the concatenated output produced by `3dpc` is inconsistent across AFNI versions; this will affect aCompCor implementations. Instead of using the concatenated output, the confound module will perform the concatenation itself from the individual PC time series, which are named consistently across AFNI versions.

Something to the effect of the following:
```
1dcat $(printf ${pc_out}'%02d'.1D' ' ${pcidx[@]}) >> ${ts}.1D
```

where `pcidx` is an array containing indices of the PCs to be retained.

**Comment by rciric** [comment]
Fixed, but there's now some redundancy in the `3dpc` calls, which future cleanup should address.

**Comment by mattcieslak** [comment]
afni version is pinned in containeried xcp
