### ISSUE TITLE
Network module community detection gamma-range titration/estimation

### ISSUE THREAD

**Issue by jaredpz** [PennBBL/xcpEngine#99]
When running genLouvain community detection there's a natural range of gamma values where gamma_min = the highest value of gamma such that every node is assigned to the same module, and gamma_max = the lowest value of gamma such that each node is assigned to its own module (i.e. n_module = n_node).

It would be a nice feature if the net module could calculate gamma_min and gamma_max automatically and then divide the interval [gamma_min, gamma_max] into an arbitrary number of even intervals and run community detection across that gamma range.

**Comment by jaredpz** [comment]
Sorry, I can't figure out how to add a label to this, but this should be a feature request and is relatively low priority

**Comment by jaredpz** [comment]
One additional thing I've realized would be useful to calculate is the gamma values at which the first community becomes a single node community.  This owuld be some intermediate gamma value between gamma_min and gamma_max that would be a useful diagnostic in helping to choose ad gamma value for biologically meaningful community detection

**Comment by mattcieslak** [comment]
community detection has been removed from xcp
